// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ActivityRepository is an autogenerated mock type for the ActivityRepository type
type ActivityRepository struct {
	mock.Mock
}

type ActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityRepository) EXPECT() *ActivityRepository_Expecter {
	return &ActivityRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, activity
func (_m *ActivityRepository) Create(ctx context.Context, activity *domain.Activity) error {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Activity) error); ok {
		r0 = rf(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActivityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ActivityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - activity *domain.Activity
func (_e *ActivityRepository_Expecter) Create(ctx interface{}, activity interface{}) *ActivityRepository_Create_Call {
	return &ActivityRepository_Create_Call{Call: _e.mock.On("Create", ctx, activity)}
}

func (_c *ActivityRepository_Create_Call) Run(run func(ctx context.Context, activity *domain.Activity)) *ActivityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Activity))
	})
	return _c
}

func (_c *ActivityRepository_Create_Call) Return(_a0 error) *ActivityRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ActivityRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Activity) error) *ActivityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function with given fields: ctx, cutoff
func (_m *ActivityRepository) DeleteOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	ret := _m.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, cutoff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, cutoff)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type ActivityRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *ActivityRepository_Expecter) DeleteOlderThan(ctx interface{}, cutoff interface{}) *ActivityRepository_DeleteOlderThan_Call {
	return &ActivityRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, cutoff)}
}

func (_c *ActivityRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, cutoff time.Time)) *ActivityRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *ActivityRepository_DeleteOlderThan_Call) Return(_a0 int64, _a1 error) *ActivityRepository_DeleteOlderThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepository_DeleteOlderThan_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *ActivityRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCoupleID provides a mock function with given fields: ctx, coupleID, limit, offset
func (_m *ActivityRepository) FindByCoupleID(ctx context.Context, coupleID string, limit int, offset int) ([]domain.Activity, error) {
	ret := _m.Called(ctx, coupleID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByCoupleID")
	}

	var r0 []domain.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Activity, error)); ok {
		return rf(ctx, coupleID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Activity); ok {
		r0 = rf(ctx, coupleID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, coupleID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepository_FindByCoupleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCoupleID'
type ActivityRepository_FindByCoupleID_Call struct {
	*mock.Call
}

// FindByCoupleID is a helper method to define mock.On call
//   - ctx context.Context
//   - coupleID string
//   - limit int
//   - offset int
func (_e *ActivityRepository_Expecter) FindByCoupleID(ctx interface{}, coupleID interface{}, limit interface{}, offset interface{}) *ActivityRepository_FindByCoupleID_Call {
	return &ActivityRepository_FindByCoupleID_Call{Call: _e.mock.On("FindByCoupleID", ctx, coupleID, limit, offset)}
}

func (_c *ActivityRepository_FindByCoupleID_Call) Run(run func(ctx context.Context, coupleID string, limit int, offset int)) *ActivityRepository_FindByCoupleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ActivityRepository_FindByCoupleID_Call) Return(_a0 []domain.Activity, _a1 error) *ActivityRepository_FindByCoupleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepository_FindByCoupleID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.Activity, error)) *ActivityRepository_FindByCoupleID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRecentByCoupleID provides a mock function with given fields: ctx, coupleID, limit
func (_m *ActivityRepository) FindRecentByCoupleID(ctx context.Context, coupleID string, limit int) ([]domain.Activity, error) {
	ret := _m.Called(ctx, coupleID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecentByCoupleID")
	}

	var r0 []domain.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.Activity, error)); ok {
		return rf(ctx, coupleID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.Activity); ok {
		r0 = rf(ctx, coupleID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, coupleID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepository_FindRecentByCoupleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRecentByCoupleID'
type ActivityRepository_FindRecentByCoupleID_Call struct {
	*mock.Call
}

// FindRecentByCoupleID is a helper method to define mock.On call
//   - ctx context.Context
//   - coupleID string
//   - limit int
func (_e *ActivityRepository_Expecter) FindRecentByCoupleID(ctx interface{}, coupleID interface{}, limit interface{}) *ActivityRepository_FindRecentByCoupleID_Call {
	return &ActivityRepository_FindRecentByCoupleID_Call{Call: _e.mock.On("FindRecentByCoupleID", ctx, coupleID, limit)}
}

func (_c *ActivityRepository_FindRecentByCoupleID_Call) Run(run func(ctx context.Context, coupleID string, limit int)) *ActivityRepository_FindRecentByCoupleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ActivityRepository_FindRecentByCoupleID_Call) Return(_a0 []domain.Activity, _a1 error) *ActivityRepository_FindRecentByCoupleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepository_FindRecentByCoupleID_Call) RunAndReturn(run func(context.Context, string, int) ([]domain.Activity, error)) *ActivityRepository_FindRecentByCoupleID_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityRepository creates a new instance of ActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepository {
	mock := &ActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
