// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// BudgetRepository is an autogenerated mock type for the BudgetRepository type
type BudgetRepository struct {
	mock.Mock
}

type BudgetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BudgetRepository) EXPECT() *BudgetRepository_Expecter {
	return &BudgetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, budget
func (_m *BudgetRepository) Create(ctx context.Context, budget *domain.MonthlyBudget) error {
	ret := _m.Called(ctx, budget)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MonthlyBudget) error); ok {
		r0 = rf(ctx, budget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BudgetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BudgetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - budget *domain.MonthlyBudget
func (_e *BudgetRepository_Expecter) Create(ctx interface{}, budget interface{}) *BudgetRepository_Create_Call {
	return &BudgetRepository_Create_Call{Call: _e.mock.On("Create", ctx, budget)}
}

func (_c *BudgetRepository_Create_Call) Run(run func(ctx context.Context, budget *domain.MonthlyBudget)) *BudgetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.MonthlyBudget))
	})
	return _c
}

func (_c *BudgetRepository_Create_Call) Return(_a0 error) *BudgetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BudgetRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.MonthlyBudget) error) *BudgetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BudgetRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BudgetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BudgetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BudgetRepository_Expecter) Delete(ctx interface{}, id interface{}) *BudgetRepository_Delete_Call {
	return &BudgetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *BudgetRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *BudgetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BudgetRepository_Delete_Call) Return(_a0 error) *BudgetRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BudgetRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *BudgetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID, year, month, limit, offset
func (_m *BudgetRepository) FindAllByUserID(ctx context.Context, userID string, year int, month int, limit int, offset int) ([]domain.MonthlyBudget, error) {
	ret := _m.Called(ctx, userID, year, month, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.MonthlyBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int, int) ([]domain.MonthlyBudget, error)); ok {
		return rf(ctx, userID, year, month, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int, int) []domain.MonthlyBudget); ok {
		r0 = rf(ctx, userID, year, month, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MonthlyBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, int, int) error); ok {
		r1 = rf(ctx, userID, year, month, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type BudgetRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
//   - limit int
//   - offset int
func (_e *BudgetRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}, year interface{}, month interface{}, limit interface{}, offset interface{}) *BudgetRepository_FindAllByUserID_Call {
	return &BudgetRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID, year, month, limit, offset)}
}

func (_c *BudgetRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string, year int, month int, limit int, offset int)) *BudgetRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *BudgetRepository_FindAllByUserID_Call) Return(_a0 []domain.MonthlyBudget, _a1 error) *BudgetRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string, int, int, int, int) ([]domain.MonthlyBudget, error)) *BudgetRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *BudgetRepository) FindByID(ctx context.Context, id string) (*domain.MonthlyBudget, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.MonthlyBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.MonthlyBudget, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.MonthlyBudget); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MonthlyBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type BudgetRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BudgetRepository_Expecter) FindByID(ctx interface{}, id interface{}) *BudgetRepository_FindByID_Call {
	return &BudgetRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *BudgetRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *BudgetRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BudgetRepository_FindByID_Call) Return(_a0 *domain.MonthlyBudget, _a1 error) *BudgetRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.MonthlyBudget, error)) *BudgetRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserCategoryPeriod provides a mock function with given fields: ctx, userID, categoryID, year, month
func (_m *BudgetRepository) FindByUserCategoryPeriod(ctx context.Context, userID string, categoryID string, year int, month int) (*domain.MonthlyBudget, error) {
	ret := _m.Called(ctx, userID, categoryID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserCategoryPeriod")
	}

	var r0 *domain.MonthlyBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) (*domain.MonthlyBudget, error)); ok {
		return rf(ctx, userID, categoryID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) *domain.MonthlyBudget); ok {
		r0 = rf(ctx, userID, categoryID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MonthlyBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, userID, categoryID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetRepository_FindByUserCategoryPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserCategoryPeriod'
type BudgetRepository_FindByUserCategoryPeriod_Call struct {
	*mock.Call
}

// FindByUserCategoryPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - categoryID string
//   - year int
//   - month int
func (_e *BudgetRepository_Expecter) FindByUserCategoryPeriod(ctx interface{}, userID interface{}, categoryID interface{}, year interface{}, month interface{}) *BudgetRepository_FindByUserCategoryPeriod_Call {
	return &BudgetRepository_FindByUserCategoryPeriod_Call{Call: _e.mock.On("FindByUserCategoryPeriod", ctx, userID, categoryID, year, month)}
}

func (_c *BudgetRepository_FindByUserCategoryPeriod_Call) Run(run func(ctx context.Context, userID string, categoryID string, year int, month int)) *BudgetRepository_FindByUserCategoryPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *BudgetRepository_FindByUserCategoryPeriod_Call) Return(_a0 *domain.MonthlyBudget, _a1 error) *BudgetRepository_FindByUserCategoryPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetRepository_FindByUserCategoryPeriod_Call) RunAndReturn(run func(context.Context, string, string, int, int) (*domain.MonthlyBudget, error)) *BudgetRepository_FindByUserCategoryPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, budget
func (_m *BudgetRepository) Update(ctx context.Context, budget *domain.MonthlyBudget) error {
	ret := _m.Called(ctx, budget)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MonthlyBudget) error); ok {
		r0 = rf(ctx, budget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BudgetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BudgetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - budget *domain.MonthlyBudget
func (_e *BudgetRepository_Expecter) Update(ctx interface{}, budget interface{}) *BudgetRepository_Update_Call {
	return &BudgetRepository_Update_Call{Call: _e.mock.On("Update", ctx, budget)}
}

func (_c *BudgetRepository_Update_Call) Run(run func(ctx context.Context, budget *domain.MonthlyBudget)) *BudgetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.MonthlyBudget))
	})
	return _c
}

func (_c *BudgetRepository_Update_Call) Return(_a0 error) *BudgetRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BudgetRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.MonthlyBudget) error) *BudgetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewBudgetRepository creates a new instance of BudgetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBudgetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BudgetRepository {
	mock := &BudgetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
