// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

type CategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryRepository) EXPECT() *CategoryRepository_Expecter {
	return &CategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, category
func (_m *CategoryRepository) Create(ctx context.Context, category *domain.Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *domain.Category
func (_e *CategoryRepository_Expecter) Create(ctx interface{}, category interface{}) *CategoryRepository_Create_Call {
	return &CategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *CategoryRepository_Create_Call) Run(run func(ctx context.Context, category *domain.Category)) *CategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Category))
	})
	return _c
}

func (_c *CategoryRepository_Create_Call) Return(_a0 error) *CategoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Category) error) *CategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *CategoryRepository_Delete_Call {
	return &CategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CategoryRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *CategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CategoryRepository_Delete_Call) Return(_a0 error) *CategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *CategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID
func (_m *CategoryRepository) FindAllByUserID(ctx context.Context, userID string) ([]domain.Category, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Category, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Category); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type CategoryRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CategoryRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}) *CategoryRepository_FindAllByUserID_Call {
	return &CategoryRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID)}
}

func (_c *CategoryRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string)) *CategoryRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CategoryRepository_FindAllByUserID_Call) Return(_a0 []domain.Category, _a1 error) *CategoryRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Category, error)) *CategoryRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) FindByID(ctx context.Context, id string) (*domain.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type CategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CategoryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *CategoryRepository_FindByID_Call {
	return &CategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *CategoryRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *CategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CategoryRepository_FindByID_Call) Return(_a0 *domain.Category, _a1 error) *CategoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Category, error)) *CategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, category
func (_m *CategoryRepository) Update(ctx context.Context, category *domain.Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *domain.Category
func (_e *CategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *CategoryRepository_Update_Call {
	return &CategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *CategoryRepository_Update_Call) Run(run func(ctx context.Context, category *domain.Category)) *CategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Category))
	})
	return _c
}

func (_c *CategoryRepository_Update_Call) Return(_a0 error) *CategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Category) error) *CategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
