// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// CoupleRepository is an autogenerated mock type for the CoupleRepository type
type CoupleRepository struct {
	mock.Mock
}

type CoupleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CoupleRepository) EXPECT() *CoupleRepository_Expecter {
	return &CoupleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, couple
func (_m *CoupleRepository) Create(ctx context.Context, couple *domain.Couple) error {
	ret := _m.Called(ctx, couple)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Couple) error); ok {
		r0 = rf(ctx, couple)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoupleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CoupleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - couple *domain.Couple
func (_e *CoupleRepository_Expecter) Create(ctx interface{}, couple interface{}) *CoupleRepository_Create_Call {
	return &CoupleRepository_Create_Call{Call: _e.mock.On("Create", ctx, couple)}
}

func (_c *CoupleRepository_Create_Call) Run(run func(ctx context.Context, couple *domain.Couple)) *CoupleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Couple))
	})
	return _c
}

func (_c *CoupleRepository_Create_Call) Return(_a0 error) *CoupleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoupleRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Couple) error) *CoupleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CoupleRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoupleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CoupleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CoupleRepository_Expecter) Delete(ctx interface{}, id interface{}) *CoupleRepository_Delete_Call {
	return &CoupleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CoupleRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *CoupleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoupleRepository_Delete_Call) Return(_a0 error) *CoupleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoupleRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *CoupleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *CoupleRepository) FindByUserID(ctx context.Context, userID string) (*domain.Couple, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *domain.Couple
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Couple, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Couple); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Couple)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoupleRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type CoupleRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CoupleRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *CoupleRepository_FindByUserID_Call {
	return &CoupleRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *CoupleRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *CoupleRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoupleRepository_FindByUserID_Call) Return(_a0 *domain.Couple, _a1 error) *CoupleRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoupleRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, string) (*domain.Couple, error)) *CoupleRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoupleRepository creates a new instance of CoupleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoupleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoupleRepository {
	mock := &CoupleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
