// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// CoupleInvitationRepository is an autogenerated mock type for the CoupleInvitationRepository type
type CoupleInvitationRepository struct {
	mock.Mock
}

type CoupleInvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CoupleInvitationRepository) EXPECT() *CoupleInvitationRepository_Expecter {
	return &CoupleInvitationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, invitation
func (_m *CoupleInvitationRepository) Create(ctx context.Context, invitation *domain.CoupleInvitation) error {
	ret := _m.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CoupleInvitation) error); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoupleInvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CoupleInvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - invitation *domain.CoupleInvitation
func (_e *CoupleInvitationRepository_Expecter) Create(ctx interface{}, invitation interface{}) *CoupleInvitationRepository_Create_Call {
	return &CoupleInvitationRepository_Create_Call{Call: _e.mock.On("Create", ctx, invitation)}
}

func (_c *CoupleInvitationRepository_Create_Call) Run(run func(ctx context.Context, invitation *domain.CoupleInvitation)) *CoupleInvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CoupleInvitation))
	})
	return _c
}

func (_c *CoupleInvitationRepository_Create_Call) Return(_a0 error) *CoupleInvitationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoupleInvitationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.CoupleInvitation) error) *CoupleInvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *CoupleInvitationRepository) FindByID(ctx context.Context, id string) (*domain.CoupleInvitation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.CoupleInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.CoupleInvitation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.CoupleInvitation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CoupleInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoupleInvitationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type CoupleInvitationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CoupleInvitationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *CoupleInvitationRepository_FindByID_Call {
	return &CoupleInvitationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *CoupleInvitationRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *CoupleInvitationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoupleInvitationRepository_FindByID_Call) Return(_a0 *domain.CoupleInvitation, _a1 error) *CoupleInvitationRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoupleInvitationRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.CoupleInvitation, error)) *CoupleInvitationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindIncomingPending provides a mock function with given fields: ctx, receiverUserID
func (_m *CoupleInvitationRepository) FindIncomingPending(ctx context.Context, receiverUserID string) ([]domain.CoupleInvitation, error) {
	ret := _m.Called(ctx, receiverUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindIncomingPending")
	}

	var r0 []domain.CoupleInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.CoupleInvitation, error)); ok {
		return rf(ctx, receiverUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.CoupleInvitation); ok {
		r0 = rf(ctx, receiverUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CoupleInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, receiverUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoupleInvitationRepository_FindIncomingPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIncomingPending'
type CoupleInvitationRepository_FindIncomingPending_Call struct {
	*mock.Call
}

// FindIncomingPending is a helper method to define mock.On call
//   - ctx context.Context
//   - receiverUserID string
func (_e *CoupleInvitationRepository_Expecter) FindIncomingPending(ctx interface{}, receiverUserID interface{}) *CoupleInvitationRepository_FindIncomingPending_Call {
	return &CoupleInvitationRepository_FindIncomingPending_Call{Call: _e.mock.On("FindIncomingPending", ctx, receiverUserID)}
}

func (_c *CoupleInvitationRepository_FindIncomingPending_Call) Run(run func(ctx context.Context, receiverUserID string)) *CoupleInvitationRepository_FindIncomingPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoupleInvitationRepository_FindIncomingPending_Call) Return(_a0 []domain.CoupleInvitation, _a1 error) *CoupleInvitationRepository_FindIncomingPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoupleInvitationRepository_FindIncomingPending_Call) RunAndReturn(run func(context.Context, string) ([]domain.CoupleInvitation, error)) *CoupleInvitationRepository_FindIncomingPending_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, invitation
func (_m *CoupleInvitationRepository) Update(ctx context.Context, invitation *domain.CoupleInvitation) error {
	ret := _m.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CoupleInvitation) error); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoupleInvitationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CoupleInvitationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - invitation *domain.CoupleInvitation
func (_e *CoupleInvitationRepository_Expecter) Update(ctx interface{}, invitation interface{}) *CoupleInvitationRepository_Update_Call {
	return &CoupleInvitationRepository_Update_Call{Call: _e.mock.On("Update", ctx, invitation)}
}

func (_c *CoupleInvitationRepository_Update_Call) Run(run func(ctx context.Context, invitation *domain.CoupleInvitation)) *CoupleInvitationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CoupleInvitation))
	})
	return _c
}

func (_c *CoupleInvitationRepository_Update_Call) Return(_a0 error) *CoupleInvitationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoupleInvitationRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.CoupleInvitation) error) *CoupleInvitationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoupleInvitationRepository creates a new instance of CoupleInvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoupleInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoupleInvitationRepository {
	mock := &CoupleInvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
