// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"
	repository "duitkita-api/repository"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type ExpenseRepository struct {
	mock.Mock
}

type ExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseRepository) EXPECT() *ExpenseRepository_Expecter {
	return &ExpenseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, expense
func (_m *ExpenseRepository) Create(ctx context.Context, expense *domain.Expense) error {
	ret := _m.Called(ctx, expense)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) error); ok {
		r0 = rf(ctx, expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ExpenseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - expense *domain.Expense
func (_e *ExpenseRepository_Expecter) Create(ctx interface{}, expense interface{}) *ExpenseRepository_Create_Call {
	return &ExpenseRepository_Create_Call{Call: _e.mock.On("Create", ctx, expense)}
}

func (_c *ExpenseRepository_Create_Call) Run(run func(ctx context.Context, expense *domain.Expense)) *ExpenseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Expense))
	})
	return _c
}

func (_c *ExpenseRepository_Create_Call) Return(_a0 error) *ExpenseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Expense) error) *ExpenseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ExpenseRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ExpenseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ExpenseRepository_Expecter) Delete(ctx interface{}, id interface{}) *ExpenseRepository_Delete_Call {
	return &ExpenseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ExpenseRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *ExpenseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExpenseRepository_Delete_Call) Return(_a0 error) *ExpenseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ExpenseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByBudgetID provides a mock function with given fields: ctx, budgetID
func (_m *ExpenseRepository) FindAllByBudgetID(ctx context.Context, budgetID string) ([]domain.Expense, error) {
	ret := _m.Called(ctx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByBudgetID")
	}

	var r0 []domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Expense, error)); ok {
		return rf(ctx, budgetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Expense); ok {
		r0 = rf(ctx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, budgetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseRepository_FindAllByBudgetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByBudgetID'
type ExpenseRepository_FindAllByBudgetID_Call struct {
	*mock.Call
}

// FindAllByBudgetID is a helper method to define mock.On call
//   - ctx context.Context
//   - budgetID string
func (_e *ExpenseRepository_Expecter) FindAllByBudgetID(ctx interface{}, budgetID interface{}) *ExpenseRepository_FindAllByBudgetID_Call {
	return &ExpenseRepository_FindAllByBudgetID_Call{Call: _e.mock.On("FindAllByBudgetID", ctx, budgetID)}
}

func (_c *ExpenseRepository_FindAllByBudgetID_Call) Run(run func(ctx context.Context, budgetID string)) *ExpenseRepository_FindAllByBudgetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExpenseRepository_FindAllByBudgetID_Call) Return(_a0 []domain.Expense, _a1 error) *ExpenseRepository_FindAllByBudgetID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseRepository_FindAllByBudgetID_Call) RunAndReturn(run func(context.Context, string) ([]domain.Expense, error)) *ExpenseRepository_FindAllByBudgetID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID, filter
func (_m *ExpenseRepository) FindAllByUserID(ctx context.Context, userID string, filter repository.ExpenseFilter) ([]domain.Expense, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.ExpenseFilter) ([]domain.Expense, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.ExpenseFilter) []domain.Expense); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repository.ExpenseFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type ExpenseRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filter repository.ExpenseFilter
func (_e *ExpenseRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}, filter interface{}) *ExpenseRepository_FindAllByUserID_Call {
	return &ExpenseRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID, filter)}
}

func (_c *ExpenseRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string, filter repository.ExpenseFilter)) *ExpenseRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(repository.ExpenseFilter))
	})
	return _c
}

func (_c *ExpenseRepository_FindAllByUserID_Call) Return(_a0 []domain.Expense, _a1 error) *ExpenseRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string, repository.ExpenseFilter) ([]domain.Expense, error)) *ExpenseRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ExpenseRepository) FindByID(ctx context.Context, id string) (*domain.Expense, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Expense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Expense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ExpenseRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ExpenseRepository_Expecter) FindByID(ctx interface{}, id interface{}) *ExpenseRepository_FindByID_Call {
	return &ExpenseRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ExpenseRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *ExpenseRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExpenseRepository_FindByID_Call) Return(_a0 *domain.Expense, _a1 error) *ExpenseRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Expense, error)) *ExpenseRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, expense
func (_m *ExpenseRepository) Update(ctx context.Context, expense *domain.Expense) error {
	ret := _m.Called(ctx, expense)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) error); ok {
		r0 = rf(ctx, expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ExpenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - expense *domain.Expense
func (_e *ExpenseRepository_Expecter) Update(ctx interface{}, expense interface{}) *ExpenseRepository_Update_Call {
	return &ExpenseRepository_Update_Call{Call: _e.mock.On("Update", ctx, expense)}
}

func (_c *ExpenseRepository_Update_Call) Run(run func(ctx context.Context, expense *domain.Expense)) *ExpenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Expense))
	})
	return _c
}

func (_c *ExpenseRepository_Update_Call) Return(_a0 error) *ExpenseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Expense) error) *ExpenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateOwnership provides a mock function with given fields: ctx, userID, categoryID, budgetID
func (_m *ExpenseRepository) ValidateOwnership(ctx context.Context, userID string, categoryID string, budgetID string) (bool, bool, error) {
	ret := _m.Called(ctx, userID, categoryID, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOwnership")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, bool, error)); ok {
		return rf(ctx, userID, categoryID, budgetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, userID, categoryID, budgetID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) bool); ok {
		r1 = rf(ctx, userID, categoryID, budgetID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, userID, categoryID, budgetID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExpenseRepository_ValidateOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateOwnership'
type ExpenseRepository_ValidateOwnership_Call struct {
	*mock.Call
}

// ValidateOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - categoryID string
//   - budgetID string
func (_e *ExpenseRepository_Expecter) ValidateOwnership(ctx interface{}, userID interface{}, categoryID interface{}, budgetID interface{}) *ExpenseRepository_ValidateOwnership_Call {
	return &ExpenseRepository_ValidateOwnership_Call{Call: _e.mock.On("ValidateOwnership", ctx, userID, categoryID, budgetID)}
}

func (_c *ExpenseRepository_ValidateOwnership_Call) Run(run func(ctx context.Context, userID string, categoryID string, budgetID string)) *ExpenseRepository_ValidateOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ExpenseRepository_ValidateOwnership_Call) Return(categoryOwned bool, budgetOwned bool, err error) *ExpenseRepository_ValidateOwnership_Call {
	_c.Call.Return(categoryOwned, budgetOwned, err)
	return _c
}

func (_c *ExpenseRepository_ValidateOwnership_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, bool, error)) *ExpenseRepository_ValidateOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpenseRepository creates a new instance of ExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseRepository {
	mock := &ExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
