// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

type NotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationRepository) EXPECT() *NotificationRepository_Expecter {
	return &NotificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, notification
func (_m *NotificationRepository) Create(ctx context.Context, notification *domain.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *domain.Notification
func (_e *NotificationRepository_Expecter) Create(ctx interface{}, notification interface{}) *NotificationRepository_Create_Call {
	return &NotificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, notification)}
}

func (_c *NotificationRepository_Create_Call) Run(run func(ctx context.Context, notification *domain.Notification)) *NotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Notification))
	})
	return _c
}

func (_c *NotificationRepository_Create_Call) Return(_a0 error) *NotificationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Notification) error) *NotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReadBefore provides a mock function with given fields: ctx, cutoff
func (_m *NotificationRepository) DeleteReadBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	ret := _m.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReadBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, cutoff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, cutoff)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_DeleteReadBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReadBefore'
type NotificationRepository_DeleteReadBefore_Call struct {
	*mock.Call
}

// DeleteReadBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *NotificationRepository_Expecter) DeleteReadBefore(ctx interface{}, cutoff interface{}) *NotificationRepository_DeleteReadBefore_Call {
	return &NotificationRepository_DeleteReadBefore_Call{Call: _e.mock.On("DeleteReadBefore", ctx, cutoff)}
}

func (_c *NotificationRepository_DeleteReadBefore_Call) Run(run func(ctx context.Context, cutoff time.Time)) *NotificationRepository_DeleteReadBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *NotificationRepository_DeleteReadBefore_Call) Return(_a0 int64, _a1 error) *NotificationRepository_DeleteReadBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_DeleteReadBefore_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *NotificationRepository_DeleteReadBefore_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *NotificationRepository) FindAllByUserID(ctx context.Context, userID string, limit int, offset int) ([]domain.Notification, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Notification, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Notification); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type NotificationRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *NotificationRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *NotificationRepository_FindAllByUserID_Call {
	return &NotificationRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID, limit, offset)}
}

func (_c *NotificationRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *NotificationRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *NotificationRepository_FindAllByUserID_Call) Return(_a0 []domain.Notification, _a1 error) *NotificationRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.Notification, error)) *NotificationRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *NotificationRepository) MarkAllRead(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationRepository_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type NotificationRepository_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *NotificationRepository_Expecter) MarkAllRead(ctx interface{}, userID interface{}) *NotificationRepository_MarkAllRead_Call {
	return &NotificationRepository_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *NotificationRepository_MarkAllRead_Call) Run(run func(ctx context.Context, userID string)) *NotificationRepository_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NotificationRepository_MarkAllRead_Call) Return(_a0 error) *NotificationRepository_MarkAllRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationRepository_MarkAllRead_Call) RunAndReturn(run func(context.Context, string) error) *NotificationRepository_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, id, userID
func (_m *NotificationRepository) MarkRead(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type NotificationRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *NotificationRepository_Expecter) MarkRead(ctx interface{}, id interface{}, userID interface{}) *NotificationRepository_MarkRead_Call {
	return &NotificationRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, id, userID)}
}

func (_c *NotificationRepository_MarkRead_Call) Run(run func(ctx context.Context, id string, userID string)) *NotificationRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *NotificationRepository_MarkRead_Call) Return(_a0 error) *NotificationRepository_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationRepository_MarkRead_Call) RunAndReturn(run func(context.Context, string, string) error) *NotificationRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
