// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// NotificationPreferenceRepository is an autogenerated mock type for the NotificationPreferenceRepository type
type NotificationPreferenceRepository struct {
	mock.Mock
}

type NotificationPreferenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationPreferenceRepository) EXPECT() *NotificationPreferenceRepository_Expecter {
	return &NotificationPreferenceRepository_Expecter{mock: &_m.Mock}
}

// FindAllByUserID provides a mock function with given fields: ctx, userID
func (_m *NotificationPreferenceRepository) FindAllByUserID(ctx context.Context, userID string) ([]domain.NotificationPreference, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.NotificationPreference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.NotificationPreference, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.NotificationPreference); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotificationPreference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationPreferenceRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type NotificationPreferenceRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *NotificationPreferenceRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}) *NotificationPreferenceRepository_FindAllByUserID_Call {
	return &NotificationPreferenceRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID)}
}

func (_c *NotificationPreferenceRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string)) *NotificationPreferenceRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NotificationPreferenceRepository_FindAllByUserID_Call) Return(_a0 []domain.NotificationPreference, _a1 error) *NotificationPreferenceRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationPreferenceRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.NotificationPreference, error)) *NotificationPreferenceRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, pref
func (_m *NotificationPreferenceRepository) Upsert(ctx context.Context, pref *domain.NotificationPreference) error {
	ret := _m.Called(ctx, pref)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NotificationPreference) error); ok {
		r0 = rf(ctx, pref)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationPreferenceRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type NotificationPreferenceRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - pref *domain.NotificationPreference
func (_e *NotificationPreferenceRepository_Expecter) Upsert(ctx interface{}, pref interface{}) *NotificationPreferenceRepository_Upsert_Call {
	return &NotificationPreferenceRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, pref)}
}

func (_c *NotificationPreferenceRepository_Upsert_Call) Run(run func(ctx context.Context, pref *domain.NotificationPreference)) *NotificationPreferenceRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.NotificationPreference))
	})
	return _c
}

func (_c *NotificationPreferenceRepository_Upsert_Call) Return(_a0 error) *NotificationPreferenceRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationPreferenceRepository_Upsert_Call) RunAndReturn(run func(context.Context, *domain.NotificationPreference) error) *NotificationPreferenceRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationPreferenceRepository creates a new instance of NotificationPreferenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationPreferenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationPreferenceRepository {
	mock := &NotificationPreferenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
