// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RecurringExpenseRepository is an autogenerated mock type for the RecurringExpenseRepository type
type RecurringExpenseRepository struct {
	mock.Mock
}

type RecurringExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RecurringExpenseRepository) EXPECT() *RecurringExpenseRepository_Expecter {
	return &RecurringExpenseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, re
func (_m *RecurringExpenseRepository) Create(ctx context.Context, re *domain.RecurringExpense) error {
	ret := _m.Called(ctx, re)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RecurringExpense) error); ok {
		r0 = rf(ctx, re)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecurringExpenseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RecurringExpenseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - re *domain.RecurringExpense
func (_e *RecurringExpenseRepository_Expecter) Create(ctx interface{}, re interface{}) *RecurringExpenseRepository_Create_Call {
	return &RecurringExpenseRepository_Create_Call{Call: _e.mock.On("Create", ctx, re)}
}

func (_c *RecurringExpenseRepository_Create_Call) Run(run func(ctx context.Context, re *domain.RecurringExpense)) *RecurringExpenseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RecurringExpense))
	})
	return _c
}

func (_c *RecurringExpenseRepository_Create_Call) Return(_a0 error) *RecurringExpenseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecurringExpenseRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.RecurringExpense) error) *RecurringExpenseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RecurringExpenseRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecurringExpenseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RecurringExpenseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RecurringExpenseRepository_Expecter) Delete(ctx interface{}, id interface{}) *RecurringExpenseRepository_Delete_Call {
	return &RecurringExpenseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *RecurringExpenseRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *RecurringExpenseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RecurringExpenseRepository_Delete_Call) Return(_a0 error) *RecurringExpenseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecurringExpenseRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *RecurringExpenseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *RecurringExpenseRepository) FindAllByUserID(ctx context.Context, userID string, limit int, offset int) ([]domain.RecurringExpense, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.RecurringExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.RecurringExpense, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.RecurringExpense); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type RecurringExpenseRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *RecurringExpenseRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *RecurringExpenseRepository_FindAllByUserID_Call {
	return &RecurringExpenseRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID, limit, offset)}
}

func (_c *RecurringExpenseRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *RecurringExpenseRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *RecurringExpenseRepository_FindAllByUserID_Call) Return(_a0 []domain.RecurringExpense, _a1 error) *RecurringExpenseRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.RecurringExpense, error)) *RecurringExpenseRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *RecurringExpenseRepository) FindByID(ctx context.Context, id string) (*domain.RecurringExpense, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.RecurringExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RecurringExpense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RecurringExpense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type RecurringExpenseRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RecurringExpenseRepository_Expecter) FindByID(ctx interface{}, id interface{}) *RecurringExpenseRepository_FindByID_Call {
	return &RecurringExpenseRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *RecurringExpenseRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *RecurringExpenseRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RecurringExpenseRepository_FindByID_Call) Return(_a0 *domain.RecurringExpense, _a1 error) *RecurringExpenseRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.RecurringExpense, error)) *RecurringExpenseRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindDue provides a mock function with given fields: ctx, asOf
func (_m *RecurringExpenseRepository) FindDue(ctx context.Context, asOf time.Time) ([]domain.RecurringExpense, error) {
	ret := _m.Called(ctx, asOf)

	if len(ret) == 0 {
		panic("no return value specified for FindDue")
	}

	var r0 []domain.RecurringExpense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.RecurringExpense, error)); ok {
		return rf(ctx, asOf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []domain.RecurringExpense); ok {
		r0 = rf(ctx, asOf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RecurringExpense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, asOf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseRepository_FindDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDue'
type RecurringExpenseRepository_FindDue_Call struct {
	*mock.Call
}

// FindDue is a helper method to define mock.On call
//   - ctx context.Context
//   - asOf time.Time
func (_e *RecurringExpenseRepository_Expecter) FindDue(ctx interface{}, asOf interface{}) *RecurringExpenseRepository_FindDue_Call {
	return &RecurringExpenseRepository_FindDue_Call{Call: _e.mock.On("FindDue", ctx, asOf)}
}

func (_c *RecurringExpenseRepository_FindDue_Call) Run(run func(ctx context.Context, asOf time.Time)) *RecurringExpenseRepository_FindDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *RecurringExpenseRepository_FindDue_Call) Return(_a0 []domain.RecurringExpense, _a1 error) *RecurringExpenseRepository_FindDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseRepository_FindDue_Call) RunAndReturn(run func(context.Context, time.Time) ([]domain.RecurringExpense, error)) *RecurringExpenseRepository_FindDue_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, re
func (_m *RecurringExpenseRepository) Update(ctx context.Context, re *domain.RecurringExpense) error {
	ret := _m.Called(ctx, re)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RecurringExpense) error); ok {
		r0 = rf(ctx, re)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecurringExpenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RecurringExpenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - re *domain.RecurringExpense
func (_e *RecurringExpenseRepository_Expecter) Update(ctx interface{}, re interface{}) *RecurringExpenseRepository_Update_Call {
	return &RecurringExpenseRepository_Update_Call{Call: _e.mock.On("Update", ctx, re)}
}

func (_c *RecurringExpenseRepository_Update_Call) Run(run func(ctx context.Context, re *domain.RecurringExpense)) *RecurringExpenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RecurringExpense))
	})
	return _c
}

func (_c *RecurringExpenseRepository_Update_Call) Return(_a0 error) *RecurringExpenseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecurringExpenseRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.RecurringExpense) error) *RecurringExpenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecurringExpenseRepository creates a new instance of RecurringExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecurringExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecurringExpenseRepository {
	mock := &RecurringExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
