// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ReminderRepository is an autogenerated mock type for the ReminderRepository type
type ReminderRepository struct {
	mock.Mock
}

type ReminderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReminderRepository) EXPECT() *ReminderRepository_Expecter {
	return &ReminderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, reminder
func (_m *ReminderRepository) Create(ctx context.Context, reminder *domain.BillReminder) error {
	ret := _m.Called(ctx, reminder)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillReminder) error); ok {
		r0 = rf(ctx, reminder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReminderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReminderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reminder *domain.BillReminder
func (_e *ReminderRepository_Expecter) Create(ctx interface{}, reminder interface{}) *ReminderRepository_Create_Call {
	return &ReminderRepository_Create_Call{Call: _e.mock.On("Create", ctx, reminder)}
}

func (_c *ReminderRepository_Create_Call) Run(run func(ctx context.Context, reminder *domain.BillReminder)) *ReminderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BillReminder))
	})
	return _c
}

func (_c *ReminderRepository_Create_Call) Return(_a0 error) *ReminderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReminderRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.BillReminder) error) *ReminderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ReminderRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReminderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReminderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReminderRepository_Expecter) Delete(ctx interface{}, id interface{}) *ReminderRepository_Delete_Call {
	return &ReminderRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ReminderRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *ReminderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReminderRepository_Delete_Call) Return(_a0 error) *ReminderRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReminderRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ReminderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *ReminderRepository) FindAllByUserID(ctx context.Context, userID string, limit int, offset int) ([]domain.BillReminder, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.BillReminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.BillReminder, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.BillReminder); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillReminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type ReminderRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *ReminderRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *ReminderRepository_FindAllByUserID_Call {
	return &ReminderRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID, limit, offset)}
}

func (_c *ReminderRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *ReminderRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReminderRepository_FindAllByUserID_Call) Return(_a0 []domain.BillReminder, _a1 error) *ReminderRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.BillReminder, error)) *ReminderRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ReminderRepository) FindByID(ctx context.Context, id string) (*domain.BillReminder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.BillReminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.BillReminder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.BillReminder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BillReminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ReminderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReminderRepository_Expecter) FindByID(ctx interface{}, id interface{}) *ReminderRepository_FindByID_Call {
	return &ReminderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ReminderRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *ReminderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReminderRepository_FindByID_Call) Return(_a0 *domain.BillReminder, _a1 error) *ReminderRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.BillReminder, error)) *ReminderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindDueForNotification provides a mock function with given fields: ctx, asOf
func (_m *ReminderRepository) FindDueForNotification(ctx context.Context, asOf time.Time) ([]domain.BillReminder, error) {
	ret := _m.Called(ctx, asOf)

	if len(ret) == 0 {
		panic("no return value specified for FindDueForNotification")
	}

	var r0 []domain.BillReminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.BillReminder, error)); ok {
		return rf(ctx, asOf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []domain.BillReminder); ok {
		r0 = rf(ctx, asOf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillReminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, asOf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderRepository_FindDueForNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDueForNotification'
type ReminderRepository_FindDueForNotification_Call struct {
	*mock.Call
}

// FindDueForNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - asOf time.Time
func (_e *ReminderRepository_Expecter) FindDueForNotification(ctx interface{}, asOf interface{}) *ReminderRepository_FindDueForNotification_Call {
	return &ReminderRepository_FindDueForNotification_Call{Call: _e.mock.On("FindDueForNotification", ctx, asOf)}
}

func (_c *ReminderRepository_FindDueForNotification_Call) Run(run func(ctx context.Context, asOf time.Time)) *ReminderRepository_FindDueForNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *ReminderRepository_FindDueForNotification_Call) Return(_a0 []domain.BillReminder, _a1 error) *ReminderRepository_FindDueForNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderRepository_FindDueForNotification_Call) RunAndReturn(run func(context.Context, time.Time) ([]domain.BillReminder, error)) *ReminderRepository_FindDueForNotification_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, reminder
func (_m *ReminderRepository) Update(ctx context.Context, reminder *domain.BillReminder) error {
	ret := _m.Called(ctx, reminder)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillReminder) error); ok {
		r0 = rf(ctx, reminder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReminderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ReminderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - reminder *domain.BillReminder
func (_e *ReminderRepository_Expecter) Update(ctx interface{}, reminder interface{}) *ReminderRepository_Update_Call {
	return &ReminderRepository_Update_Call{Call: _e.mock.On("Update", ctx, reminder)}
}

func (_c *ReminderRepository_Update_Call) Run(run func(ctx context.Context, reminder *domain.BillReminder)) *ReminderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BillReminder))
	})
	return _c
}

func (_c *ReminderRepository_Update_Call) Return(_a0 error) *ReminderRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReminderRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.BillReminder) error) *ReminderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewReminderRepository creates a new instance of ReminderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReminderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReminderRepository {
	mock := &ReminderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
