// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReportExportRepository is an autogenerated mock type for the ReportExportRepository type
type ReportExportRepository struct {
	mock.Mock
}

type ReportExportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportExportRepository) EXPECT() *ReportExportRepository_Expecter {
	return &ReportExportRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, export
func (_m *ReportExportRepository) Create(ctx context.Context, export *domain.ReportExport) error {
	ret := _m.Called(ctx, export)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReportExport) error); ok {
		r0 = rf(ctx, export)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportExportRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReportExportRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - export *domain.ReportExport
func (_e *ReportExportRepository_Expecter) Create(ctx interface{}, export interface{}) *ReportExportRepository_Create_Call {
	return &ReportExportRepository_Create_Call{Call: _e.mock.On("Create", ctx, export)}
}

func (_c *ReportExportRepository_Create_Call) Run(run func(ctx context.Context, export *domain.ReportExport)) *ReportExportRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ReportExport))
	})
	return _c
}

func (_c *ReportExportRepository_Create_Call) Return(_a0 error) *ReportExportRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportExportRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.ReportExport) error) *ReportExportRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function with given fields: ctx, userID
func (_m *ReportExportRepository) FindAllByUserID(ctx context.Context, userID string) ([]domain.ReportExport, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []domain.ReportExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.ReportExport, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.ReportExport); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReportExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type ReportExportRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ReportExportRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}) *ReportExportRepository_FindAllByUserID_Call {
	return &ReportExportRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID)}
}

func (_c *ReportExportRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID string)) *ReportExportRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReportExportRepository_FindAllByUserID_Call) Return(_a0 []domain.ReportExport, _a1 error) *ReportExportRepository_FindAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportRepository_FindAllByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.ReportExport, error)) *ReportExportRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ReportExportRepository) FindByID(ctx context.Context, id string) (*domain.ReportExport, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.ReportExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ReportExport, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ReportExport); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReportExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ReportExportRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReportExportRepository_Expecter) FindByID(ctx interface{}, id interface{}) *ReportExportRepository_FindByID_Call {
	return &ReportExportRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ReportExportRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *ReportExportRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReportExportRepository_FindByID_Call) Return(_a0 *domain.ReportExport, _a1 error) *ReportExportRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.ReportExport, error)) *ReportExportRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPending provides a mock function with given fields: ctx
func (_m *ReportExportRepository) FindPending(ctx context.Context) ([]domain.ReportExport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindPending")
	}

	var r0 []domain.ReportExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ReportExport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ReportExport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReportExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportRepository_FindPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPending'
type ReportExportRepository_FindPending_Call struct {
	*mock.Call
}

// FindPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportExportRepository_Expecter) FindPending(ctx interface{}) *ReportExportRepository_FindPending_Call {
	return &ReportExportRepository_FindPending_Call{Call: _e.mock.On("FindPending", ctx)}
}

func (_c *ReportExportRepository_FindPending_Call) Run(run func(ctx context.Context)) *ReportExportRepository_FindPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportExportRepository_FindPending_Call) Return(_a0 []domain.ReportExport, _a1 error) *ReportExportRepository_FindPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportRepository_FindPending_Call) RunAndReturn(run func(context.Context) ([]domain.ReportExport, error)) *ReportExportRepository_FindPending_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, export
func (_m *ReportExportRepository) Update(ctx context.Context, export *domain.ReportExport) error {
	ret := _m.Called(ctx, export)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReportExport) error); ok {
		r0 = rf(ctx, export)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportExportRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ReportExportRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - export *domain.ReportExport
func (_e *ReportExportRepository_Expecter) Update(ctx interface{}, export interface{}) *ReportExportRepository_Update_Call {
	return &ReportExportRepository_Update_Call{Call: _e.mock.On("Update", ctx, export)}
}

func (_c *ReportExportRepository_Update_Call) Run(run func(ctx context.Context, export *domain.ReportExport)) *ReportExportRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ReportExport))
	})
	return _c
}

func (_c *ReportExportRepository_Update_Call) Return(_a0 error) *ReportExportRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportExportRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.ReportExport) error) *ReportExportRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportExportRepository creates a new instance of ReportExportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportExportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportExportRepository {
	mock := &ReportExportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
