// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repository "duitkita-api/repository"

	mock "github.com/stretchr/testify/mock"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

type ReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportRepository) EXPECT() *ReportRepository_Expecter {
	return &ReportRepository_Expecter{mock: &_m.Mock}
}

// MonthlyTrend provides a mock function with given fields: ctx, userID, months
func (_m *ReportRepository) MonthlyTrend(ctx context.Context, userID string, months int) ([]repository.MonthTotal, error) {
	ret := _m.Called(ctx, userID, months)

	if len(ret) == 0 {
		panic("no return value specified for MonthlyTrend")
	}

	var r0 []repository.MonthTotal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]repository.MonthTotal, error)); ok {
		return rf(ctx, userID, months)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []repository.MonthTotal); ok {
		r0 = rf(ctx, userID, months)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.MonthTotal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, months)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_MonthlyTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonthlyTrend'
type ReportRepository_MonthlyTrend_Call struct {
	*mock.Call
}

// MonthlyTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - months int
func (_e *ReportRepository_Expecter) MonthlyTrend(ctx interface{}, userID interface{}, months interface{}) *ReportRepository_MonthlyTrend_Call {
	return &ReportRepository_MonthlyTrend_Call{Call: _e.mock.On("MonthlyTrend", ctx, userID, months)}
}

func (_c *ReportRepository_MonthlyTrend_Call) Run(run func(ctx context.Context, userID string, months int)) *ReportRepository_MonthlyTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ReportRepository_MonthlyTrend_Call) Return(_a0 []repository.MonthTotal, _a1 error) *ReportRepository_MonthlyTrend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_MonthlyTrend_Call) RunAndReturn(run func(context.Context, string, int) ([]repository.MonthTotal, error)) *ReportRepository_MonthlyTrend_Call {
	_c.Call.Return(run)
	return _c
}

// MonthlyTrendByCategory provides a mock function with given fields: ctx, userID, categoryID, months
func (_m *ReportRepository) MonthlyTrendByCategory(ctx context.Context, userID string, categoryID string, months int) ([]repository.MonthTotal, error) {
	ret := _m.Called(ctx, userID, categoryID, months)

	if len(ret) == 0 {
		panic("no return value specified for MonthlyTrendByCategory")
	}

	var r0 []repository.MonthTotal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) ([]repository.MonthTotal, error)); ok {
		return rf(ctx, userID, categoryID, months)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []repository.MonthTotal); ok {
		r0 = rf(ctx, userID, categoryID, months)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.MonthTotal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, userID, categoryID, months)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_MonthlyTrendByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonthlyTrendByCategory'
type ReportRepository_MonthlyTrendByCategory_Call struct {
	*mock.Call
}

// MonthlyTrendByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - categoryID string
//   - months int
func (_e *ReportRepository_Expecter) MonthlyTrendByCategory(ctx interface{}, userID interface{}, categoryID interface{}, months interface{}) *ReportRepository_MonthlyTrendByCategory_Call {
	return &ReportRepository_MonthlyTrendByCategory_Call{Call: _e.mock.On("MonthlyTrendByCategory", ctx, userID, categoryID, months)}
}

func (_c *ReportRepository_MonthlyTrendByCategory_Call) Run(run func(ctx context.Context, userID string, categoryID string, months int)) *ReportRepository_MonthlyTrendByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *ReportRepository_MonthlyTrendByCategory_Call) Return(_a0 []repository.MonthTotal, _a1 error) *ReportRepository_MonthlyTrendByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_MonthlyTrendByCategory_Call) RunAndReturn(run func(context.Context, string, string, int) ([]repository.MonthTotal, error)) *ReportRepository_MonthlyTrendByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// SpentByCategoryForPeriod provides a mock function with given fields: ctx, userID, year, month
func (_m *ReportRepository) SpentByCategoryForPeriod(ctx context.Context, userID string, year int, month int) ([]repository.CategoryTotal, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for SpentByCategoryForPeriod")
	}

	var r0 []repository.CategoryTotal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]repository.CategoryTotal, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []repository.CategoryTotal); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CategoryTotal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_SpentByCategoryForPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpentByCategoryForPeriod'
type ReportRepository_SpentByCategoryForPeriod_Call struct {
	*mock.Call
}

// SpentByCategoryForPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *ReportRepository_Expecter) SpentByCategoryForPeriod(ctx interface{}, userID interface{}, year interface{}, month interface{}) *ReportRepository_SpentByCategoryForPeriod_Call {
	return &ReportRepository_SpentByCategoryForPeriod_Call{Call: _e.mock.On("SpentByCategoryForPeriod", ctx, userID, year, month)}
}

func (_c *ReportRepository_SpentByCategoryForPeriod_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *ReportRepository_SpentByCategoryForPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReportRepository_SpentByCategoryForPeriod_Call) Return(_a0 []repository.CategoryTotal, _a1 error) *ReportRepository_SpentByCategoryForPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_SpentByCategoryForPeriod_Call) RunAndReturn(run func(context.Context, string, int, int) ([]repository.CategoryTotal, error)) *ReportRepository_SpentByCategoryForPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// SpentByDayForPeriod provides a mock function with given fields: ctx, userID, year, month
func (_m *ReportRepository) SpentByDayForPeriod(ctx context.Context, userID string, year int, month int) ([]repository.DayTotal, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for SpentByDayForPeriod")
	}

	var r0 []repository.DayTotal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]repository.DayTotal, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []repository.DayTotal); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DayTotal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_SpentByDayForPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpentByDayForPeriod'
type ReportRepository_SpentByDayForPeriod_Call struct {
	*mock.Call
}

// SpentByDayForPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *ReportRepository_Expecter) SpentByDayForPeriod(ctx interface{}, userID interface{}, year interface{}, month interface{}) *ReportRepository_SpentByDayForPeriod_Call {
	return &ReportRepository_SpentByDayForPeriod_Call{Call: _e.mock.On("SpentByDayForPeriod", ctx, userID, year, month)}
}

func (_c *ReportRepository_SpentByDayForPeriod_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *ReportRepository_SpentByDayForPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReportRepository_SpentByDayForPeriod_Call) Return(_a0 []repository.DayTotal, _a1 error) *ReportRepository_SpentByDayForPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_SpentByDayForPeriod_Call) RunAndReturn(run func(context.Context, string, int, int) ([]repository.DayTotal, error)) *ReportRepository_SpentByDayForPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// SumBudgetByUserAndPeriod provides a mock function with given fields: ctx, userID, year, month
func (_m *ReportRepository) SumBudgetByUserAndPeriod(ctx context.Context, userID string, year int, month int) (int64, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for SumBudgetByUserAndPeriod")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (int64, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) int64); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_SumBudgetByUserAndPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumBudgetByUserAndPeriod'
type ReportRepository_SumBudgetByUserAndPeriod_Call struct {
	*mock.Call
}

// SumBudgetByUserAndPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *ReportRepository_Expecter) SumBudgetByUserAndPeriod(ctx interface{}, userID interface{}, year interface{}, month interface{}) *ReportRepository_SumBudgetByUserAndPeriod_Call {
	return &ReportRepository_SumBudgetByUserAndPeriod_Call{Call: _e.mock.On("SumBudgetByUserAndPeriod", ctx, userID, year, month)}
}

func (_c *ReportRepository_SumBudgetByUserAndPeriod_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *ReportRepository_SumBudgetByUserAndPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReportRepository_SumBudgetByUserAndPeriod_Call) Return(_a0 int64, _a1 error) *ReportRepository_SumBudgetByUserAndPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_SumBudgetByUserAndPeriod_Call) RunAndReturn(run func(context.Context, string, int, int) (int64, error)) *ReportRepository_SumBudgetByUserAndPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// SumExpensesByUserAndPeriod provides a mock function with given fields: ctx, userID, year, month
func (_m *ReportRepository) SumExpensesByUserAndPeriod(ctx context.Context, userID string, year int, month int) (int64, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for SumExpensesByUserAndPeriod")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (int64, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) int64); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_SumExpensesByUserAndPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumExpensesByUserAndPeriod'
type ReportRepository_SumExpensesByUserAndPeriod_Call struct {
	*mock.Call
}

// SumExpensesByUserAndPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *ReportRepository_Expecter) SumExpensesByUserAndPeriod(ctx interface{}, userID interface{}, year interface{}, month interface{}) *ReportRepository_SumExpensesByUserAndPeriod_Call {
	return &ReportRepository_SumExpensesByUserAndPeriod_Call{Call: _e.mock.On("SumExpensesByUserAndPeriod", ctx, userID, year, month)}
}

func (_c *ReportRepository_SumExpensesByUserAndPeriod_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *ReportRepository_SumExpensesByUserAndPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReportRepository_SumExpensesByUserAndPeriod_Call) Return(_a0 int64, _a1 error) *ReportRepository_SumExpensesByUserAndPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_SumExpensesByUserAndPeriod_Call) RunAndReturn(run func(context.Context, string, int, int) (int64, error)) *ReportRepository_SumExpensesByUserAndPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
