// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SecurityAuditRepository is an autogenerated mock type for the SecurityAuditRepository type
type SecurityAuditRepository struct {
	mock.Mock
}

type SecurityAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SecurityAuditRepository) EXPECT() *SecurityAuditRepository_Expecter {
	return &SecurityAuditRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, log
func (_m *SecurityAuditRepository) Create(ctx context.Context, log *domain.SecurityAuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SecurityAuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SecurityAuditRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SecurityAuditRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *domain.SecurityAuditLog
func (_e *SecurityAuditRepository_Expecter) Create(ctx interface{}, log interface{}) *SecurityAuditRepository_Create_Call {
	return &SecurityAuditRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *SecurityAuditRepository_Create_Call) Run(run func(ctx context.Context, log *domain.SecurityAuditLog)) *SecurityAuditRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.SecurityAuditLog))
	})
	return _c
}

func (_c *SecurityAuditRepository_Create_Call) Return(_a0 error) *SecurityAuditRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SecurityAuditRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.SecurityAuditLog) error) *SecurityAuditRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function with given fields: ctx, cutoff
func (_m *SecurityAuditRepository) DeleteOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	ret := _m.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, cutoff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, cutoff)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecurityAuditRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type SecurityAuditRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *SecurityAuditRepository_Expecter) DeleteOlderThan(ctx interface{}, cutoff interface{}) *SecurityAuditRepository_DeleteOlderThan_Call {
	return &SecurityAuditRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, cutoff)}
}

func (_c *SecurityAuditRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, cutoff time.Time)) *SecurityAuditRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *SecurityAuditRepository_DeleteOlderThan_Call) Return(_a0 int64, _a1 error) *SecurityAuditRepository_DeleteOlderThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecurityAuditRepository_DeleteOlderThan_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *SecurityAuditRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID, limit
func (_m *SecurityAuditRepository) FindByUserID(ctx context.Context, userID string, limit int) ([]domain.SecurityAuditLog, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []domain.SecurityAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.SecurityAuditLog, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.SecurityAuditLog); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SecurityAuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecurityAuditRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type SecurityAuditRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *SecurityAuditRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}, limit interface{}) *SecurityAuditRepository_FindByUserID_Call {
	return &SecurityAuditRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID, limit)}
}

func (_c *SecurityAuditRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string, limit int)) *SecurityAuditRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *SecurityAuditRepository_FindByUserID_Call) Return(_a0 []domain.SecurityAuditLog, _a1 error) *SecurityAuditRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecurityAuditRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, string, int) ([]domain.SecurityAuditLog, error)) *SecurityAuditRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewSecurityAuditRepository creates a new instance of SecurityAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityAuditRepository {
	mock := &SecurityAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
