// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UserSessionRepository is an autogenerated mock type for the UserSessionRepository type
type UserSessionRepository struct {
	mock.Mock
}

type UserSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSessionRepository) EXPECT() *UserSessionRepository_Expecter {
	return &UserSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *UserSessionRepository) Create(ctx context.Context, session *domain.UserSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.UserSession
func (_e *UserSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *UserSessionRepository_Create_Call {
	return &UserSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *UserSessionRepository_Create_Call) Run(run func(ctx context.Context, session *domain.UserSession)) *UserSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UserSession))
	})
	return _c
}

func (_c *UserSessionRepository_Create_Call) Return(_a0 error) *UserSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserSessionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.UserSession) error) *UserSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStale provides a mock function with given fields: ctx, cutoff
func (_m *UserSessionRepository) DeleteStale(ctx context.Context, cutoff time.Time) (int64, error) {
	ret := _m.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStale")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, cutoff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, cutoff)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSessionRepository_DeleteStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStale'
type UserSessionRepository_DeleteStale_Call struct {
	*mock.Call
}

// DeleteStale is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *UserSessionRepository_Expecter) DeleteStale(ctx interface{}, cutoff interface{}) *UserSessionRepository_DeleteStale_Call {
	return &UserSessionRepository_DeleteStale_Call{Call: _e.mock.On("DeleteStale", ctx, cutoff)}
}

func (_c *UserSessionRepository_DeleteStale_Call) Run(run func(ctx context.Context, cutoff time.Time)) *UserSessionRepository_DeleteStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *UserSessionRepository_DeleteStale_Call) Return(_a0 int64, _a1 error) *UserSessionRepository_DeleteStale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserSessionRepository_DeleteStale_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *UserSessionRepository_DeleteStale_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *UserSessionRepository) FindActiveByUserID(ctx context.Context, userID string) ([]domain.UserSession, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserID")
	}

	var r0 []domain.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.UserSession, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.UserSession); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSessionRepository_FindActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserID'
type UserSessionRepository_FindActiveByUserID_Call struct {
	*mock.Call
}

// FindActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserSessionRepository_Expecter) FindActiveByUserID(ctx interface{}, userID interface{}) *UserSessionRepository_FindActiveByUserID_Call {
	return &UserSessionRepository_FindActiveByUserID_Call{Call: _e.mock.On("FindActiveByUserID", ctx, userID)}
}

func (_c *UserSessionRepository_FindActiveByUserID_Call) Run(run func(ctx context.Context, userID string)) *UserSessionRepository_FindActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserSessionRepository_FindActiveByUserID_Call) Return(_a0 []domain.UserSession, _a1 error) *UserSessionRepository_FindActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserSessionRepository_FindActiveByUserID_Call) RunAndReturn(run func(context.Context, string) ([]domain.UserSession, error)) *UserSessionRepository_FindActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *UserSessionRepository) FindByID(ctx context.Context, id string) (*domain.UserSession, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserSession, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserSession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSessionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserSessionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserSessionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *UserSessionRepository_FindByID_Call {
	return &UserSessionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserSessionRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *UserSessionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserSessionRepository_FindByID_Call) Return(_a0 *domain.UserSession, _a1 error) *UserSessionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserSessionRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*domain.UserSession, error)) *UserSessionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllExcept provides a mock function with given fields: ctx, userID, exceptSessionID
func (_m *UserSessionRepository) RevokeAllExcept(ctx context.Context, userID string, exceptSessionID string) error {
	ret := _m.Called(ctx, userID, exceptSessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllExcept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, exceptSessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserSessionRepository_RevokeAllExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllExcept'
type UserSessionRepository_RevokeAllExcept_Call struct {
	*mock.Call
}

// RevokeAllExcept is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - exceptSessionID string
func (_e *UserSessionRepository_Expecter) RevokeAllExcept(ctx interface{}, userID interface{}, exceptSessionID interface{}) *UserSessionRepository_RevokeAllExcept_Call {
	return &UserSessionRepository_RevokeAllExcept_Call{Call: _e.mock.On("RevokeAllExcept", ctx, userID, exceptSessionID)}
}

func (_c *UserSessionRepository_RevokeAllExcept_Call) Run(run func(ctx context.Context, userID string, exceptSessionID string)) *UserSessionRepository_RevokeAllExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserSessionRepository_RevokeAllExcept_Call) Return(_a0 error) *UserSessionRepository_RevokeAllExcept_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserSessionRepository_RevokeAllExcept_Call) RunAndReturn(run func(context.Context, string, string) error) *UserSessionRepository_RevokeAllExcept_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function with given fields: ctx, id
func (_m *UserSessionRepository) RevokeByID(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserSessionRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type UserSessionRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserSessionRepository_Expecter) RevokeByID(ctx interface{}, id interface{}) *UserSessionRepository_RevokeByID_Call {
	return &UserSessionRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *UserSessionRepository_RevokeByID_Call) Run(run func(ctx context.Context, id string)) *UserSessionRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserSessionRepository_RevokeByID_Call) Return(_a0 error) *UserSessionRepository_RevokeByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserSessionRepository_RevokeByID_Call) RunAndReturn(run func(context.Context, string) error) *UserSessionRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, session
func (_m *UserSessionRepository) Update(ctx context.Context, session *domain.UserSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserSessionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserSessionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.UserSession
func (_e *UserSessionRepository_Expecter) Update(ctx interface{}, session interface{}) *UserSessionRepository_Update_Call {
	return &UserSessionRepository_Update_Call{Call: _e.mock.On("Update", ctx, session)}
}

func (_c *UserSessionRepository_Update_Call) Run(run func(ctx context.Context, session *domain.UserSession)) *UserSessionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UserSession))
	})
	return _c
}

func (_c *UserSessionRepository_Update_Call) Return(_a0 error) *UserSessionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserSessionRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.UserSession) error) *UserSessionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserSessionRepository creates a new instance of UserSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSessionRepository {
	mock := &UserSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
