// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"
	service "duitkita-api/service"

	mock "github.com/stretchr/testify/mock"
)

// ActivityService is an autogenerated mock type for the ActivityService type
type ActivityService struct {
	mock.Mock
}

type ActivityService_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityService) EXPECT() *ActivityService_Expecter {
	return &ActivityService_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, userID, limit, offset
func (_m *ActivityService) List(ctx context.Context, userID string, limit int, offset int) ([]service.ActivityItem, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.ActivityItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]service.ActivityItem, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []service.ActivityItem); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ActivityItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ActivityService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *ActivityService_Expecter) List(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *ActivityService_List_Call {
	return &ActivityService_List_Call{Call: _e.mock.On("List", ctx, userID, limit, offset)}
}

func (_c *ActivityService_List_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *ActivityService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ActivityService_List_Call) Return(_a0 []service.ActivityItem, _a1 error) *ActivityService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityService_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]service.ActivityItem, error)) *ActivityService_List_Call {
	_c.Call.Return(run)
	return _c
}

// LogActivity provides a mock function with given fields: ctx, actorID, action, entityType, entityID, meta
func (_m *ActivityService) LogActivity(ctx context.Context, actorID string, action domain.ActivityAction, entityType domain.ActivityEntityType, entityID string, meta map[string]interface{}) {
	_m.Called(ctx, actorID, action, entityType, entityID, meta)
}

// ActivityService_LogActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogActivity'
type ActivityService_LogActivity_Call struct {
	*mock.Call
}

// LogActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - action domain.ActivityAction
//   - entityType domain.ActivityEntityType
//   - entityID string
//   - meta map[string]interface{}
func (_e *ActivityService_Expecter) LogActivity(ctx interface{}, actorID interface{}, action interface{}, entityType interface{}, entityID interface{}, meta interface{}) *ActivityService_LogActivity_Call {
	return &ActivityService_LogActivity_Call{Call: _e.mock.On("LogActivity", ctx, actorID, action, entityType, entityID, meta)}
}

func (_c *ActivityService_LogActivity_Call) Run(run func(ctx context.Context, actorID string, action domain.ActivityAction, entityType domain.ActivityEntityType, entityID string, meta map[string]interface{})) *ActivityService_LogActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ActivityAction), args[3].(domain.ActivityEntityType), args[4].(string), args[5].(map[string]interface{}))
	})
	return _c
}

func (_c *ActivityService_LogActivity_Call) Return() *ActivityService_LogActivity_Call {
	_c.Call.Return()
	return _c
}

func (_c *ActivityService_LogActivity_Call) RunAndReturn(run func(context.Context, string, domain.ActivityAction, domain.ActivityEntityType, string, map[string]interface{})) *ActivityService_LogActivity_Call {
	_c.Run(run)
	return _c
}

// Recent provides a mock function with given fields: ctx, userID, limit
func (_m *ActivityService) Recent(ctx context.Context, userID string, limit int) ([]service.ActivityItem, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for Recent")
	}

	var r0 []service.ActivityItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]service.ActivityItem, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []service.ActivityItem); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ActivityItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityService_Recent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recent'
type ActivityService_Recent_Call struct {
	*mock.Call
}

// Recent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *ActivityService_Expecter) Recent(ctx interface{}, userID interface{}, limit interface{}) *ActivityService_Recent_Call {
	return &ActivityService_Recent_Call{Call: _e.mock.On("Recent", ctx, userID, limit)}
}

func (_c *ActivityService_Recent_Call) Run(run func(ctx context.Context, userID string, limit int)) *ActivityService_Recent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ActivityService_Recent_Call) Return(_a0 []service.ActivityItem, _a1 error) *ActivityService_Recent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityService_Recent_Call) RunAndReturn(run func(context.Context, string, int) ([]service.ActivityItem, error)) *ActivityService_Recent_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityService creates a new instance of ActivityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityService {
	mock := &ActivityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
