// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// ForgotPassword provides a mock function with given fields: ctx, req
func (_m *AuthService) ForgotPassword(ctx context.Context, req request.ForgotPasswordRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.ForgotPasswordRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type AuthService_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.ForgotPasswordRequest
func (_e *AuthService_Expecter) ForgotPassword(ctx interface{}, req interface{}) *AuthService_ForgotPassword_Call {
	return &AuthService_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, req)}
}

func (_c *AuthService_ForgotPassword_Call) Run(run func(ctx context.Context, req request.ForgotPasswordRequest)) *AuthService_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.ForgotPasswordRequest))
	})
	return _c
}

func (_c *AuthService_ForgotPassword_Call) Return(_a0 error) *AuthService_ForgotPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_ForgotPassword_Call) RunAndReturn(run func(context.Context, request.ForgotPasswordRequest) error) *AuthService_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx, userID
func (_m *AuthService) ListSessions(ctx context.Context, userID string) ([]response.SessionResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []response.SessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]response.SessionResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []response.SessionResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.SessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type AuthService_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AuthService_Expecter) ListSessions(ctx interface{}, userID interface{}) *AuthService_ListSessions_Call {
	return &AuthService_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, userID)}
}

func (_c *AuthService_ListSessions_Call) Run(run func(ctx context.Context, userID string)) *AuthService_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_ListSessions_Call) Return(_a0 []response.SessionResponse, _a1 error) *AuthService_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_ListSessions_Call) RunAndReturn(run func(context.Context, string) ([]response.SessionResponse, error)) *AuthService_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req, ip, userAgent
func (_m *AuthService) Login(ctx context.Context, req request.LoginRequest, ip string, userAgent string) (*response.AuthResponse, error) {
	ret := _m.Called(ctx, req, ip, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *response.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.LoginRequest, string, string) (*response.AuthResponse, error)); ok {
		return rf(ctx, req, ip, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.LoginRequest, string, string) *response.AuthResponse); ok {
		r0 = rf(ctx, req, ip, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.LoginRequest, string, string) error); ok {
		r1 = rf(ctx, req, ip, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.LoginRequest
//   - ip string
//   - userAgent string
func (_e *AuthService_Expecter) Login(ctx interface{}, req interface{}, ip interface{}, userAgent interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, req, ip, userAgent)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, req request.LoginRequest, ip string, userAgent string)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.LoginRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 *response.AuthResponse, _a1 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(context.Context, request.LoginRequest, string, string) (*response.AuthResponse, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, req
func (_m *AuthService) Refresh(ctx context.Context, req request.RefreshTokenRequest) (*response.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *response.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.RefreshTokenRequest) (*response.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.RefreshTokenRequest) *response.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.RefreshTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.RefreshTokenRequest
func (_e *AuthService_Expecter) Refresh(ctx interface{}, req interface{}) *AuthService_Refresh_Call {
	return &AuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, req)}
}

func (_c *AuthService_Refresh_Call) Run(run func(ctx context.Context, req request.RefreshTokenRequest)) *AuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.RefreshTokenRequest))
	})
	return _c
}

func (_c *AuthService_Refresh_Call) Return(_a0 *response.AuthResponse, _a1 error) *AuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Refresh_Call) RunAndReturn(run func(context.Context, request.RefreshTokenRequest) (*response.AuthResponse, error)) *AuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req, ip, userAgent
func (_m *AuthService) Register(ctx context.Context, req request.RegisterRequest, ip string, userAgent string) (*response.RegisterResponse, error) {
	ret := _m.Called(ctx, req, ip, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *response.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.RegisterRequest, string, string) (*response.RegisterResponse, error)); ok {
		return rf(ctx, req, ip, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.RegisterRequest, string, string) *response.RegisterResponse); ok {
		r0 = rf(ctx, req, ip, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.RegisterRequest, string, string) error); ok {
		r1 = rf(ctx, req, ip, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.RegisterRequest
//   - ip string
//   - userAgent string
func (_e *AuthService_Expecter) Register(ctx interface{}, req interface{}, ip interface{}, userAgent interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, req, ip, userAgent)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, req request.RegisterRequest, ip string, userAgent string)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.RegisterRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 *response.RegisterResponse, _a1 error) *AuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(context.Context, request.RegisterRequest, string, string) (*response.RegisterResponse, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResendOTP provides a mock function with given fields: ctx, req
func (_m *AuthService) ResendOTP(ctx context.Context, req request.ResendOTPRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.ResendOTPRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_ResendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendOTP'
type AuthService_ResendOTP_Call struct {
	*mock.Call
}

// ResendOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.ResendOTPRequest
func (_e *AuthService_Expecter) ResendOTP(ctx interface{}, req interface{}) *AuthService_ResendOTP_Call {
	return &AuthService_ResendOTP_Call{Call: _e.mock.On("ResendOTP", ctx, req)}
}

func (_c *AuthService_ResendOTP_Call) Run(run func(ctx context.Context, req request.ResendOTPRequest)) *AuthService_ResendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.ResendOTPRequest))
	})
	return _c
}

func (_c *AuthService_ResendOTP_Call) Return(_a0 error) *AuthService_ResendOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_ResendOTP_Call) RunAndReturn(run func(context.Context, request.ResendOTPRequest) error) *AuthService_ResendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, req
func (_m *AuthService) ResetPassword(ctx context.Context, req request.ResetPasswordRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.ResetPasswordRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type AuthService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.ResetPasswordRequest
func (_e *AuthService_Expecter) ResetPassword(ctx interface{}, req interface{}) *AuthService_ResetPassword_Call {
	return &AuthService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, req)}
}

func (_c *AuthService_ResetPassword_Call) Run(run func(ctx context.Context, req request.ResetPasswordRequest)) *AuthService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.ResetPasswordRequest))
	})
	return _c
}

func (_c *AuthService_ResetPassword_Call) Return(_a0 error) *AuthService_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_ResetPassword_Call) RunAndReturn(run func(context.Context, request.ResetPasswordRequest) error) *AuthService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeOtherSessions provides a mock function with given fields: ctx, userID, currentSessionID
func (_m *AuthService) RevokeOtherSessions(ctx context.Context, userID string, currentSessionID string) error {
	ret := _m.Called(ctx, userID, currentSessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeOtherSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, currentSessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_RevokeOtherSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeOtherSessions'
type AuthService_RevokeOtherSessions_Call struct {
	*mock.Call
}

// RevokeOtherSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - currentSessionID string
func (_e *AuthService_Expecter) RevokeOtherSessions(ctx interface{}, userID interface{}, currentSessionID interface{}) *AuthService_RevokeOtherSessions_Call {
	return &AuthService_RevokeOtherSessions_Call{Call: _e.mock.On("RevokeOtherSessions", ctx, userID, currentSessionID)}
}

func (_c *AuthService_RevokeOtherSessions_Call) Run(run func(ctx context.Context, userID string, currentSessionID string)) *AuthService_RevokeOtherSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthService_RevokeOtherSessions_Call) Return(_a0 error) *AuthService_RevokeOtherSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_RevokeOtherSessions_Call) RunAndReturn(run func(context.Context, string, string) error) *AuthService_RevokeOtherSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, userID, sessionID
func (_m *AuthService) RevokeSession(ctx context.Context, userID string, sessionID string) error {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type AuthService_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *AuthService_Expecter) RevokeSession(ctx interface{}, userID interface{}, sessionID interface{}) *AuthService_RevokeSession_Call {
	return &AuthService_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, userID, sessionID)}
}

func (_c *AuthService_RevokeSession_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *AuthService_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthService_RevokeSession_Call) Return(_a0 error) *AuthService_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_RevokeSession_Call) RunAndReturn(run func(context.Context, string, string) error) *AuthService_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function with given fields: ctx, req, ip, userAgent
func (_m *AuthService) VerifyOTP(ctx context.Context, req request.VerifyOTPRequest, ip string, userAgent string) (*response.AuthResponse, error) {
	ret := _m.Called(ctx, req, ip, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 *response.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.VerifyOTPRequest, string, string) (*response.AuthResponse, error)); ok {
		return rf(ctx, req, ip, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.VerifyOTPRequest, string, string) *response.AuthResponse); ok {
		r0 = rf(ctx, req, ip, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.VerifyOTPRequest, string, string) error); ok {
		r1 = rf(ctx, req, ip, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type AuthService_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.VerifyOTPRequest
//   - ip string
//   - userAgent string
func (_e *AuthService_Expecter) VerifyOTP(ctx interface{}, req interface{}, ip interface{}, userAgent interface{}) *AuthService_VerifyOTP_Call {
	return &AuthService_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, req, ip, userAgent)}
}

func (_c *AuthService_VerifyOTP_Call) Run(run func(ctx context.Context, req request.VerifyOTPRequest, ip string, userAgent string)) *AuthService_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.VerifyOTPRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AuthService_VerifyOTP_Call) Return(_a0 *response.AuthResponse, _a1 error) *AuthService_VerifyOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_VerifyOTP_Call) RunAndReturn(run func(context.Context, request.VerifyOTPRequest, string, string) (*response.AuthResponse, error)) *AuthService_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
