// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// BudgetService is an autogenerated mock type for the BudgetService type
type BudgetService struct {
	mock.Mock
}

type BudgetService_Expecter struct {
	mock *mock.Mock
}

func (_m *BudgetService) EXPECT() *BudgetService_Expecter {
	return &BudgetService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *BudgetService) Create(ctx context.Context, userID string, req request.CreateBudgetRequest) (*response.BudgetResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.BudgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateBudgetRequest) (*response.BudgetResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateBudgetRequest) *response.BudgetResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BudgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.CreateBudgetRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BudgetService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.CreateBudgetRequest
func (_e *BudgetService_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *BudgetService_Create_Call {
	return &BudgetService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *BudgetService_Create_Call) Run(run func(ctx context.Context, userID string, req request.CreateBudgetRequest)) *BudgetService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.CreateBudgetRequest))
	})
	return _c
}

func (_c *BudgetService_Create_Call) Return(_a0 *response.BudgetResponse, _a1 error) *BudgetService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetService_Create_Call) RunAndReturn(run func(context.Context, string, request.CreateBudgetRequest) (*response.BudgetResponse, error)) *BudgetService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *BudgetService) Delete(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BudgetService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BudgetService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *BudgetService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *BudgetService_Delete_Call {
	return &BudgetService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *BudgetService_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *BudgetService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *BudgetService_Delete_Call) Return(_a0 error) *BudgetService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BudgetService_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *BudgetService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Finalize provides a mock function with given fields: ctx, userID, id
func (_m *BudgetService) Finalize(ctx context.Context, userID string, id string) (*response.BudgetResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Finalize")
	}

	var r0 *response.BudgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.BudgetResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.BudgetResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BudgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetService_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type BudgetService_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *BudgetService_Expecter) Finalize(ctx interface{}, userID interface{}, id interface{}) *BudgetService_Finalize_Call {
	return &BudgetService_Finalize_Call{Call: _e.mock.On("Finalize", ctx, userID, id)}
}

func (_c *BudgetService_Finalize_Call) Run(run func(ctx context.Context, userID string, id string)) *BudgetService_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *BudgetService_Finalize_Call) Return(_a0 *response.BudgetResponse, _a1 error) *BudgetService_Finalize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetService_Finalize_Call) RunAndReturn(run func(context.Context, string, string) (*response.BudgetResponse, error)) *BudgetService_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *BudgetService) GetByID(ctx context.Context, userID string, id string) (*response.BudgetResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.BudgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.BudgetResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.BudgetResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BudgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type BudgetService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *BudgetService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *BudgetService_GetByID_Call {
	return &BudgetService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *BudgetService_GetByID_Call) Run(run func(ctx context.Context, userID string, id string)) *BudgetService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *BudgetService_GetByID_Call) Return(_a0 *response.BudgetResponse, _a1 error) *BudgetService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetService_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*response.BudgetResponse, error)) *BudgetService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPartnerBudgets provides a mock function with given fields: ctx, userID, year, month, limit, offset
func (_m *BudgetService) GetPartnerBudgets(ctx context.Context, userID string, year int, month int, limit int, offset int) ([]response.BudgetResponse, error) {
	ret := _m.Called(ctx, userID, year, month, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPartnerBudgets")
	}

	var r0 []response.BudgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int, int) ([]response.BudgetResponse, error)); ok {
		return rf(ctx, userID, year, month, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int, int) []response.BudgetResponse); ok {
		r0 = rf(ctx, userID, year, month, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.BudgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, int, int) error); ok {
		r1 = rf(ctx, userID, year, month, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetService_GetPartnerBudgets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPartnerBudgets'
type BudgetService_GetPartnerBudgets_Call struct {
	*mock.Call
}

// GetPartnerBudgets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
//   - limit int
//   - offset int
func (_e *BudgetService_Expecter) GetPartnerBudgets(ctx interface{}, userID interface{}, year interface{}, month interface{}, limit interface{}, offset interface{}) *BudgetService_GetPartnerBudgets_Call {
	return &BudgetService_GetPartnerBudgets_Call{Call: _e.mock.On("GetPartnerBudgets", ctx, userID, year, month, limit, offset)}
}

func (_c *BudgetService_GetPartnerBudgets_Call) Run(run func(ctx context.Context, userID string, year int, month int, limit int, offset int)) *BudgetService_GetPartnerBudgets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *BudgetService_GetPartnerBudgets_Call) Return(_a0 []response.BudgetResponse, _a1 error) *BudgetService_GetPartnerBudgets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetService_GetPartnerBudgets_Call) RunAndReturn(run func(context.Context, string, int, int, int, int) ([]response.BudgetResponse, error)) *BudgetService_GetPartnerBudgets_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, year, month, limit, offset
func (_m *BudgetService) List(ctx context.Context, userID string, year int, month int, limit int, offset int) ([]response.BudgetResponse, error) {
	ret := _m.Called(ctx, userID, year, month, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []response.BudgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int, int) ([]response.BudgetResponse, error)); ok {
		return rf(ctx, userID, year, month, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int, int) []response.BudgetResponse); ok {
		r0 = rf(ctx, userID, year, month, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.BudgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, int, int) error); ok {
		r1 = rf(ctx, userID, year, month, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type BudgetService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
//   - limit int
//   - offset int
func (_e *BudgetService_Expecter) List(ctx interface{}, userID interface{}, year interface{}, month interface{}, limit interface{}, offset interface{}) *BudgetService_List_Call {
	return &BudgetService_List_Call{Call: _e.mock.On("List", ctx, userID, year, month, limit, offset)}
}

func (_c *BudgetService_List_Call) Run(run func(ctx context.Context, userID string, year int, month int, limit int, offset int)) *BudgetService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *BudgetService_List_Call) Return(_a0 []response.BudgetResponse, _a1 error) *BudgetService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetService_List_Call) RunAndReturn(run func(context.Context, string, int, int, int, int) ([]response.BudgetResponse, error)) *BudgetService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, id, req
func (_m *BudgetService) Update(ctx context.Context, userID string, id string, req request.UpdateBudgetRequest) (*response.BudgetResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *response.BudgetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateBudgetRequest) (*response.BudgetResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateBudgetRequest) *response.BudgetResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BudgetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, request.UpdateBudgetRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BudgetService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - req request.UpdateBudgetRequest
func (_e *BudgetService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, req interface{}) *BudgetService_Update_Call {
	return &BudgetService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, req)}
}

func (_c *BudgetService_Update_Call) Run(run func(ctx context.Context, userID string, id string, req request.UpdateBudgetRequest)) *BudgetService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request.UpdateBudgetRequest))
	})
	return _c
}

func (_c *BudgetService_Update_Call) Return(_a0 *response.BudgetResponse, _a1 error) *BudgetService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetService_Update_Call) RunAndReturn(run func(context.Context, string, string, request.UpdateBudgetRequest) (*response.BudgetResponse, error)) *BudgetService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewBudgetService creates a new instance of BudgetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBudgetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BudgetService {
	mock := &BudgetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
