// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

type CategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryService) EXPECT() *CategoryService_Expecter {
	return &CategoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *CategoryService) Create(ctx context.Context, userID string, req request.CreateCategoryRequest) (*response.CategoryResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateCategoryRequest) (*response.CategoryResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateCategoryRequest) *response.CategoryResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.CreateCategoryRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.CreateCategoryRequest
func (_e *CategoryService_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *CategoryService_Create_Call {
	return &CategoryService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *CategoryService_Create_Call) Run(run func(ctx context.Context, userID string, req request.CreateCategoryRequest)) *CategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.CreateCategoryRequest))
	})
	return _c
}

func (_c *CategoryService_Create_Call) Return(_a0 *response.CategoryResponse, _a1 error) *CategoryService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryService_Create_Call) RunAndReturn(run func(context.Context, string, request.CreateCategoryRequest) (*response.CategoryResponse, error)) *CategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *CategoryService) Delete(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *CategoryService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *CategoryService_Delete_Call {
	return &CategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *CategoryService_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *CategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CategoryService_Delete_Call) Return(_a0 error) *CategoryService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryService_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *CategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *CategoryService) GetByID(ctx context.Context, userID string, id string) (*response.CategoryResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.CategoryResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.CategoryResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CategoryService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *CategoryService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *CategoryService_GetByID_Call {
	return &CategoryService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *CategoryService_GetByID_Call) Run(run func(ctx context.Context, userID string, id string)) *CategoryService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CategoryService_GetByID_Call) Return(_a0 *response.CategoryResponse, _a1 error) *CategoryService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryService_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*response.CategoryResponse, error)) *CategoryService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *CategoryService) List(ctx context.Context, userID string) ([]response.CategoryResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []response.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]response.CategoryResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []response.CategoryResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CategoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CategoryService_Expecter) List(ctx interface{}, userID interface{}) *CategoryService_List_Call {
	return &CategoryService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *CategoryService_List_Call) Run(run func(ctx context.Context, userID string)) *CategoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CategoryService_List_Call) Return(_a0 []response.CategoryResponse, _a1 error) *CategoryService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryService_List_Call) RunAndReturn(run func(context.Context, string) ([]response.CategoryResponse, error)) *CategoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, id, req
func (_m *CategoryService) Update(ctx context.Context, userID string, id string, req request.UpdateCategoryRequest) (*response.CategoryResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *response.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateCategoryRequest) (*response.CategoryResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateCategoryRequest) *response.CategoryResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, request.UpdateCategoryRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - req request.UpdateCategoryRequest
func (_e *CategoryService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, req interface{}) *CategoryService_Update_Call {
	return &CategoryService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, req)}
}

func (_c *CategoryService_Update_Call) Run(run func(ctx context.Context, userID string, id string, req request.UpdateCategoryRequest)) *CategoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request.UpdateCategoryRequest))
	})
	return _c
}

func (_c *CategoryService_Update_Call) Return(_a0 *response.CategoryResponse, _a1 error) *CategoryService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryService_Update_Call) RunAndReturn(run func(context.Context, string, string, request.UpdateCategoryRequest) (*response.CategoryResponse, error)) *CategoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
