// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// CoupleService is an autogenerated mock type for the CoupleService type
type CoupleService struct {
	mock.Mock
}

type CoupleService_Expecter struct {
	mock *mock.Mock
}

func (_m *CoupleService) EXPECT() *CoupleService_Expecter {
	return &CoupleService_Expecter{mock: &_m.Mock}
}

// AcceptInvitation provides a mock function with given fields: ctx, userID, invitationID
func (_m *CoupleService) AcceptInvitation(ctx context.Context, userID string, invitationID string) (*response.CoupleResponse, error) {
	ret := _m.Called(ctx, userID, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvitation")
	}

	var r0 *response.CoupleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.CoupleResponse, error)); ok {
		return rf(ctx, userID, invitationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.CoupleResponse); ok {
		r0 = rf(ctx, userID, invitationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CoupleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, invitationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoupleService_AcceptInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvitation'
type CoupleService_AcceptInvitation_Call struct {
	*mock.Call
}

// AcceptInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - invitationID string
func (_e *CoupleService_Expecter) AcceptInvitation(ctx interface{}, userID interface{}, invitationID interface{}) *CoupleService_AcceptInvitation_Call {
	return &CoupleService_AcceptInvitation_Call{Call: _e.mock.On("AcceptInvitation", ctx, userID, invitationID)}
}

func (_c *CoupleService_AcceptInvitation_Call) Run(run func(ctx context.Context, userID string, invitationID string)) *CoupleService_AcceptInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CoupleService_AcceptInvitation_Call) Return(_a0 *response.CoupleResponse, _a1 error) *CoupleService_AcceptInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoupleService_AcceptInvitation_Call) RunAndReturn(run func(context.Context, string, string) (*response.CoupleResponse, error)) *CoupleService_AcceptInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CancelInvitation provides a mock function with given fields: ctx, userID, invitationID
func (_m *CoupleService) CancelInvitation(ctx context.Context, userID string, invitationID string) error {
	ret := _m.Called(ctx, userID, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, invitationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoupleService_CancelInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelInvitation'
type CoupleService_CancelInvitation_Call struct {
	*mock.Call
}

// CancelInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - invitationID string
func (_e *CoupleService_Expecter) CancelInvitation(ctx interface{}, userID interface{}, invitationID interface{}) *CoupleService_CancelInvitation_Call {
	return &CoupleService_CancelInvitation_Call{Call: _e.mock.On("CancelInvitation", ctx, userID, invitationID)}
}

func (_c *CoupleService_CancelInvitation_Call) Run(run func(ctx context.Context, userID string, invitationID string)) *CoupleService_CancelInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CoupleService_CancelInvitation_Call) Return(_a0 error) *CoupleService_CancelInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoupleService_CancelInvitation_Call) RunAndReturn(run func(context.Context, string, string) error) *CoupleService_CancelInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetPartner provides a mock function with given fields: ctx, userID
func (_m *CoupleService) GetPartner(ctx context.Context, userID string) (*response.CoupleResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPartner")
	}

	var r0 *response.CoupleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.CoupleResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.CoupleResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CoupleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoupleService_GetPartner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPartner'
type CoupleService_GetPartner_Call struct {
	*mock.Call
}

// GetPartner is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CoupleService_Expecter) GetPartner(ctx interface{}, userID interface{}) *CoupleService_GetPartner_Call {
	return &CoupleService_GetPartner_Call{Call: _e.mock.On("GetPartner", ctx, userID)}
}

func (_c *CoupleService_GetPartner_Call) Run(run func(ctx context.Context, userID string)) *CoupleService_GetPartner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoupleService_GetPartner_Call) Return(_a0 *response.CoupleResponse, _a1 error) *CoupleService_GetPartner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoupleService_GetPartner_Call) RunAndReturn(run func(context.Context, string) (*response.CoupleResponse, error)) *CoupleService_GetPartner_Call {
	_c.Call.Return(run)
	return _c
}

// ListIncomingInvitations provides a mock function with given fields: ctx, userID
func (_m *CoupleService) ListIncomingInvitations(ctx context.Context, userID string) ([]response.InvitationResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListIncomingInvitations")
	}

	var r0 []response.InvitationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]response.InvitationResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []response.InvitationResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.InvitationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoupleService_ListIncomingInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIncomingInvitations'
type CoupleService_ListIncomingInvitations_Call struct {
	*mock.Call
}

// ListIncomingInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CoupleService_Expecter) ListIncomingInvitations(ctx interface{}, userID interface{}) *CoupleService_ListIncomingInvitations_Call {
	return &CoupleService_ListIncomingInvitations_Call{Call: _e.mock.On("ListIncomingInvitations", ctx, userID)}
}

func (_c *CoupleService_ListIncomingInvitations_Call) Run(run func(ctx context.Context, userID string)) *CoupleService_ListIncomingInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoupleService_ListIncomingInvitations_Call) Return(_a0 []response.InvitationResponse, _a1 error) *CoupleService_ListIncomingInvitations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoupleService_ListIncomingInvitations_Call) RunAndReturn(run func(context.Context, string) ([]response.InvitationResponse, error)) *CoupleService_ListIncomingInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// RejectInvitation provides a mock function with given fields: ctx, userID, invitationID
func (_m *CoupleService) RejectInvitation(ctx context.Context, userID string, invitationID string) error {
	ret := _m.Called(ctx, userID, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for RejectInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, invitationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoupleService_RejectInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectInvitation'
type CoupleService_RejectInvitation_Call struct {
	*mock.Call
}

// RejectInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - invitationID string
func (_e *CoupleService_Expecter) RejectInvitation(ctx interface{}, userID interface{}, invitationID interface{}) *CoupleService_RejectInvitation_Call {
	return &CoupleService_RejectInvitation_Call{Call: _e.mock.On("RejectInvitation", ctx, userID, invitationID)}
}

func (_c *CoupleService_RejectInvitation_Call) Run(run func(ctx context.Context, userID string, invitationID string)) *CoupleService_RejectInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CoupleService_RejectInvitation_Call) Return(_a0 error) *CoupleService_RejectInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoupleService_RejectInvitation_Call) RunAndReturn(run func(context.Context, string, string) error) *CoupleService_RejectInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// SendInvitation provides a mock function with given fields: ctx, senderID, req
func (_m *CoupleService) SendInvitation(ctx context.Context, senderID string, req request.SendInvitationRequest) (*response.InvitationResponse, error) {
	ret := _m.Called(ctx, senderID, req)

	if len(ret) == 0 {
		panic("no return value specified for SendInvitation")
	}

	var r0 *response.InvitationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.SendInvitationRequest) (*response.InvitationResponse, error)); ok {
		return rf(ctx, senderID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.SendInvitationRequest) *response.InvitationResponse); ok {
		r0 = rf(ctx, senderID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.InvitationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.SendInvitationRequest) error); ok {
		r1 = rf(ctx, senderID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoupleService_SendInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInvitation'
type CoupleService_SendInvitation_Call struct {
	*mock.Call
}

// SendInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID string
//   - req request.SendInvitationRequest
func (_e *CoupleService_Expecter) SendInvitation(ctx interface{}, senderID interface{}, req interface{}) *CoupleService_SendInvitation_Call {
	return &CoupleService_SendInvitation_Call{Call: _e.mock.On("SendInvitation", ctx, senderID, req)}
}

func (_c *CoupleService_SendInvitation_Call) Run(run func(ctx context.Context, senderID string, req request.SendInvitationRequest)) *CoupleService_SendInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.SendInvitationRequest))
	})
	return _c
}

func (_c *CoupleService_SendInvitation_Call) Return(_a0 *response.InvitationResponse, _a1 error) *CoupleService_SendInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoupleService_SendInvitation_Call) RunAndReturn(run func(context.Context, string, request.SendInvitationRequest) (*response.InvitationResponse, error)) *CoupleService_SendInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// Unlink provides a mock function with given fields: ctx, userID
func (_m *CoupleService) Unlink(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Unlink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoupleService_Unlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlink'
type CoupleService_Unlink_Call struct {
	*mock.Call
}

// Unlink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CoupleService_Expecter) Unlink(ctx interface{}, userID interface{}) *CoupleService_Unlink_Call {
	return &CoupleService_Unlink_Call{Call: _e.mock.On("Unlink", ctx, userID)}
}

func (_c *CoupleService_Unlink_Call) Run(run func(ctx context.Context, userID string)) *CoupleService_Unlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoupleService_Unlink_Call) Return(_a0 error) *CoupleService_Unlink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoupleService_Unlink_Call) RunAndReturn(run func(context.Context, string) error) *CoupleService_Unlink_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoupleService creates a new instance of CoupleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoupleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoupleService {
	mock := &CoupleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
