// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"
	service "duitkita-api/service"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseService is an autogenerated mock type for the ExpenseService type
type ExpenseService struct {
	mock.Mock
}

type ExpenseService_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseService) EXPECT() *ExpenseService_Expecter {
	return &ExpenseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *ExpenseService) Create(ctx context.Context, userID string, req request.CreateExpenseRequest) (*response.ExpenseResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateExpenseRequest) (*response.ExpenseResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateExpenseRequest) *response.ExpenseResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.CreateExpenseRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ExpenseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.CreateExpenseRequest
func (_e *ExpenseService_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *ExpenseService_Create_Call {
	return &ExpenseService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *ExpenseService_Create_Call) Run(run func(ctx context.Context, userID string, req request.CreateExpenseRequest)) *ExpenseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.CreateExpenseRequest))
	})
	return _c
}

func (_c *ExpenseService_Create_Call) Return(_a0 *response.ExpenseResponse, _a1 error) *ExpenseService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseService_Create_Call) RunAndReturn(run func(context.Context, string, request.CreateExpenseRequest) (*response.ExpenseResponse, error)) *ExpenseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *ExpenseService) Delete(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ExpenseService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ExpenseService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *ExpenseService_Delete_Call {
	return &ExpenseService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *ExpenseService_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *ExpenseService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ExpenseService_Delete_Call) Return(_a0 error) *ExpenseService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseService_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *ExpenseService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *ExpenseService) GetByID(ctx context.Context, userID string, id string) (*response.ExpenseResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.ExpenseResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.ExpenseResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ExpenseService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ExpenseService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *ExpenseService_GetByID_Call {
	return &ExpenseService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *ExpenseService_GetByID_Call) Run(run func(ctx context.Context, userID string, id string)) *ExpenseService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ExpenseService_GetByID_Call) Return(_a0 *response.ExpenseResponse, _a1 error) *ExpenseService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseService_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*response.ExpenseResponse, error)) *ExpenseService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, filter
func (_m *ExpenseService) List(ctx context.Context, userID string, filter service.ExpenseListFilter) ([]response.ExpenseResponse, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []response.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.ExpenseListFilter) ([]response.ExpenseResponse, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.ExpenseListFilter) []response.ExpenseResponse); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.ExpenseListFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ExpenseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filter service.ExpenseListFilter
func (_e *ExpenseService_Expecter) List(ctx interface{}, userID interface{}, filter interface{}) *ExpenseService_List_Call {
	return &ExpenseService_List_Call{Call: _e.mock.On("List", ctx, userID, filter)}
}

func (_c *ExpenseService_List_Call) Run(run func(ctx context.Context, userID string, filter service.ExpenseListFilter)) *ExpenseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(service.ExpenseListFilter))
	})
	return _c
}

func (_c *ExpenseService_List_Call) Return(_a0 []response.ExpenseResponse, _a1 error) *ExpenseService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseService_List_Call) RunAndReturn(run func(context.Context, string, service.ExpenseListFilter) ([]response.ExpenseResponse, error)) *ExpenseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByBudget provides a mock function with given fields: ctx, userID, budgetID
func (_m *ExpenseService) ListByBudget(ctx context.Context, userID string, budgetID string) ([]response.ExpenseResponse, error) {
	ret := _m.Called(ctx, userID, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for ListByBudget")
	}

	var r0 []response.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]response.ExpenseResponse, error)); ok {
		return rf(ctx, userID, budgetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []response.ExpenseResponse); ok {
		r0 = rf(ctx, userID, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, budgetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseService_ListByBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByBudget'
type ExpenseService_ListByBudget_Call struct {
	*mock.Call
}

// ListByBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - budgetID string
func (_e *ExpenseService_Expecter) ListByBudget(ctx interface{}, userID interface{}, budgetID interface{}) *ExpenseService_ListByBudget_Call {
	return &ExpenseService_ListByBudget_Call{Call: _e.mock.On("ListByBudget", ctx, userID, budgetID)}
}

func (_c *ExpenseService_ListByBudget_Call) Run(run func(ctx context.Context, userID string, budgetID string)) *ExpenseService_ListByBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ExpenseService_ListByBudget_Call) Return(_a0 []response.ExpenseResponse, _a1 error) *ExpenseService_ListByBudget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseService_ListByBudget_Call) RunAndReturn(run func(context.Context, string, string) ([]response.ExpenseResponse, error)) *ExpenseService_ListByBudget_Call {
	_c.Call.Return(run)
	return _c
}

// ListPartnerExpenses provides a mock function with given fields: ctx, userID, filter
func (_m *ExpenseService) ListPartnerExpenses(ctx context.Context, userID string, filter service.ExpenseListFilter) ([]response.ExpenseResponse, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPartnerExpenses")
	}

	var r0 []response.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.ExpenseListFilter) ([]response.ExpenseResponse, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.ExpenseListFilter) []response.ExpenseResponse); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.ExpenseListFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseService_ListPartnerExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPartnerExpenses'
type ExpenseService_ListPartnerExpenses_Call struct {
	*mock.Call
}

// ListPartnerExpenses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filter service.ExpenseListFilter
func (_e *ExpenseService_Expecter) ListPartnerExpenses(ctx interface{}, userID interface{}, filter interface{}) *ExpenseService_ListPartnerExpenses_Call {
	return &ExpenseService_ListPartnerExpenses_Call{Call: _e.mock.On("ListPartnerExpenses", ctx, userID, filter)}
}

func (_c *ExpenseService_ListPartnerExpenses_Call) Run(run func(ctx context.Context, userID string, filter service.ExpenseListFilter)) *ExpenseService_ListPartnerExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(service.ExpenseListFilter))
	})
	return _c
}

func (_c *ExpenseService_ListPartnerExpenses_Call) Return(_a0 []response.ExpenseResponse, _a1 error) *ExpenseService_ListPartnerExpenses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseService_ListPartnerExpenses_Call) RunAndReturn(run func(context.Context, string, service.ExpenseListFilter) ([]response.ExpenseResponse, error)) *ExpenseService_ListPartnerExpenses_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, id, req
func (_m *ExpenseService) Update(ctx context.Context, userID string, id string, req request.UpdateExpenseRequest) (*response.ExpenseResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *response.ExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateExpenseRequest) (*response.ExpenseResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateExpenseRequest) *response.ExpenseResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, request.UpdateExpenseRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ExpenseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - req request.UpdateExpenseRequest
func (_e *ExpenseService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, req interface{}) *ExpenseService_Update_Call {
	return &ExpenseService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, req)}
}

func (_c *ExpenseService_Update_Call) Run(run func(ctx context.Context, userID string, id string, req request.UpdateExpenseRequest)) *ExpenseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request.UpdateExpenseRequest))
	})
	return _c
}

func (_c *ExpenseService_Update_Call) Return(_a0 *response.ExpenseResponse, _a1 error) *ExpenseService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseService_Update_Call) RunAndReturn(run func(context.Context, string, string, request.UpdateExpenseRequest) (*response.ExpenseResponse, error)) *ExpenseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpenseService creates a new instance of ExpenseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseService {
	mock := &ExpenseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
