// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// FileStorage is an autogenerated mock type for the FileStorage type
type FileStorage struct {
	mock.Mock
}

type FileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *FileStorage) EXPECT() *FileStorage_Expecter {
	return &FileStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, objectKey
func (_m *FileStorage) Delete(ctx context.Context, objectKey string) error {
	ret := _m.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, objectKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FileStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *FileStorage_Expecter) Delete(ctx interface{}, objectKey interface{}) *FileStorage_Delete_Call {
	return &FileStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, objectKey)}
}

func (_c *FileStorage_Delete_Call) Run(run func(ctx context.Context, objectKey string)) *FileStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileStorage_Delete_Call) Return(_a0 error) *FileStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *FileStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// SignedURL provides a mock function with given fields: objectKey, expiry
func (_m *FileStorage) SignedURL(objectKey string, expiry time.Duration) (string, error) {
	ret := _m.Called(objectKey, expiry)

	if len(ret) == 0 {
		panic("no return value specified for SignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(objectKey, expiry)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(objectKey, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(objectKey, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileStorage_SignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignedURL'
type FileStorage_SignedURL_Call struct {
	*mock.Call
}

// SignedURL is a helper method to define mock.On call
//   - objectKey string
//   - expiry time.Duration
func (_e *FileStorage_Expecter) SignedURL(objectKey interface{}, expiry interface{}) *FileStorage_SignedURL_Call {
	return &FileStorage_SignedURL_Call{Call: _e.mock.On("SignedURL", objectKey, expiry)}
}

func (_c *FileStorage_SignedURL_Call) Run(run func(objectKey string, expiry time.Duration)) *FileStorage_SignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *FileStorage_SignedURL_Call) Return(_a0 string, _a1 error) *FileStorage_SignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileStorage_SignedURL_Call) RunAndReturn(run func(string, time.Duration) (string, error)) *FileStorage_SignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, objectKey, data, contentType
func (_m *FileStorage) Upload(ctx context.Context, objectKey string, data io.Reader, contentType string) (string, error) {
	ret := _m.Called(ctx, objectKey, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) (string, error)); ok {
		return rf(ctx, objectKey, data, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) string); ok {
		r0 = rf(ctx, objectKey, data, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, string) error); ok {
		r1 = rf(ctx, objectKey, data, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type FileStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - data io.Reader
//   - contentType string
func (_e *FileStorage_Expecter) Upload(ctx interface{}, objectKey interface{}, data interface{}, contentType interface{}) *FileStorage_Upload_Call {
	return &FileStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, objectKey, data, contentType)}
}

func (_c *FileStorage_Upload_Call) Run(run func(ctx context.Context, objectKey string, data io.Reader, contentType string)) *FileStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(string))
	})
	return _c
}

func (_c *FileStorage_Upload_Call) Return(_a0 string, _a1 error) *FileStorage_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileStorage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, string) (string, error)) *FileStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileStorage creates a new instance of FileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileStorage {
	mock := &FileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
