// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// InsightsService is an autogenerated mock type for the InsightsService type
type InsightsService struct {
	mock.Mock
}

type InsightsService_Expecter struct {
	mock *mock.Mock
}

func (_m *InsightsService) EXPECT() *InsightsService_Expecter {
	return &InsightsService_Expecter{mock: &_m.Mock}
}

// Forecast provides a mock function with given fields: ctx, userID
func (_m *InsightsService) Forecast(ctx context.Context, userID string) (*response.ForecastResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Forecast")
	}

	var r0 *response.ForecastResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.ForecastResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.ForecastResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ForecastResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsightsService_Forecast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forecast'
type InsightsService_Forecast_Call struct {
	*mock.Call
}

// Forecast is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *InsightsService_Expecter) Forecast(ctx interface{}, userID interface{}) *InsightsService_Forecast_Call {
	return &InsightsService_Forecast_Call{Call: _e.mock.On("Forecast", ctx, userID)}
}

func (_c *InsightsService_Forecast_Call) Run(run func(ctx context.Context, userID string)) *InsightsService_Forecast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InsightsService_Forecast_Call) Return(_a0 *response.ForecastResponse, _a1 error) *InsightsService_Forecast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InsightsService_Forecast_Call) RunAndReturn(run func(context.Context, string) (*response.ForecastResponse, error)) *InsightsService_Forecast_Call {
	_c.Call.Return(run)
	return _c
}

// HealthScore provides a mock function with given fields: ctx, userID, year, month
func (_m *InsightsService) HealthScore(ctx context.Context, userID string, year int, month int) (*response.HealthScoreResponse, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for HealthScore")
	}

	var r0 *response.HealthScoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*response.HealthScoreResponse, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *response.HealthScoreResponse); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.HealthScoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsightsService_HealthScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthScore'
type InsightsService_HealthScore_Call struct {
	*mock.Call
}

// HealthScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *InsightsService_Expecter) HealthScore(ctx interface{}, userID interface{}, year interface{}, month interface{}) *InsightsService_HealthScore_Call {
	return &InsightsService_HealthScore_Call{Call: _e.mock.On("HealthScore", ctx, userID, year, month)}
}

func (_c *InsightsService_HealthScore_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *InsightsService_HealthScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *InsightsService_HealthScore_Call) Return(_a0 *response.HealthScoreResponse, _a1 error) *InsightsService_HealthScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InsightsService_HealthScore_Call) RunAndReturn(run func(context.Context, string, int, int) (*response.HealthScoreResponse, error)) *InsightsService_HealthScore_Call {
	_c.Call.Return(run)
	return _c
}

// NewInsightsService creates a new instance of InsightsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInsightsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InsightsService {
	mock := &InsightsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
