// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	service "duitkita-api/service"

	mock "github.com/stretchr/testify/mock"
)

// MaintenanceService is an autogenerated mock type for the MaintenanceService type
type MaintenanceService struct {
	mock.Mock
}

type MaintenanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MaintenanceService) EXPECT() *MaintenanceService_Expecter {
	return &MaintenanceService_Expecter{mock: &_m.Mock}
}

// RunCleanup provides a mock function with given fields: ctx
func (_m *MaintenanceService) RunCleanup(ctx context.Context) (service.CleanupResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunCleanup")
	}

	var r0 service.CleanupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.CleanupResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.CleanupResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(service.CleanupResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaintenanceService_RunCleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCleanup'
type MaintenanceService_RunCleanup_Call struct {
	*mock.Call
}

// RunCleanup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MaintenanceService_Expecter) RunCleanup(ctx interface{}) *MaintenanceService_RunCleanup_Call {
	return &MaintenanceService_RunCleanup_Call{Call: _e.mock.On("RunCleanup", ctx)}
}

func (_c *MaintenanceService_RunCleanup_Call) Run(run func(ctx context.Context)) *MaintenanceService_RunCleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MaintenanceService_RunCleanup_Call) Return(_a0 service.CleanupResult, _a1 error) *MaintenanceService_RunCleanup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MaintenanceService_RunCleanup_Call) RunAndReturn(run func(context.Context) (service.CleanupResult, error)) *MaintenanceService_RunCleanup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMaintenanceService creates a new instance of MaintenanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaintenanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaintenanceService {
	mock := &MaintenanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
