// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

type NotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationService) EXPECT() *NotificationService_Expecter {
	return &NotificationService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, notifType, title, body
func (_m *NotificationService) Create(ctx context.Context, userID string, notifType domain.NotificationType, title string, body string) error {
	ret := _m.Called(ctx, userID, notifType, title, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.NotificationType, string, string) error); ok {
		r0 = rf(ctx, userID, notifType, title, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NotificationService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - notifType domain.NotificationType
//   - title string
//   - body string
func (_e *NotificationService_Expecter) Create(ctx interface{}, userID interface{}, notifType interface{}, title interface{}, body interface{}) *NotificationService_Create_Call {
	return &NotificationService_Create_Call{Call: _e.mock.On("Create", ctx, userID, notifType, title, body)}
}

func (_c *NotificationService_Create_Call) Run(run func(ctx context.Context, userID string, notifType domain.NotificationType, title string, body string)) *NotificationService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.NotificationType), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *NotificationService_Create_Call) Return(_a0 error) *NotificationService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_Create_Call) RunAndReturn(run func(context.Context, string, domain.NotificationType, string, string) error) *NotificationService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreferences provides a mock function with given fields: ctx, userID
func (_m *NotificationService) GetPreferences(ctx context.Context, userID string) (*response.NotificationPreferenceResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 *response.NotificationPreferenceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.NotificationPreferenceResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.NotificationPreferenceResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.NotificationPreferenceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationService_GetPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreferences'
type NotificationService_GetPreferences_Call struct {
	*mock.Call
}

// GetPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *NotificationService_Expecter) GetPreferences(ctx interface{}, userID interface{}) *NotificationService_GetPreferences_Call {
	return &NotificationService_GetPreferences_Call{Call: _e.mock.On("GetPreferences", ctx, userID)}
}

func (_c *NotificationService_GetPreferences_Call) Run(run func(ctx context.Context, userID string)) *NotificationService_GetPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NotificationService_GetPreferences_Call) Return(_a0 *response.NotificationPreferenceResponse, _a1 error) *NotificationService_GetPreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationService_GetPreferences_Call) RunAndReturn(run func(context.Context, string) (*response.NotificationPreferenceResponse, error)) *NotificationService_GetPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, limit, offset
func (_m *NotificationService) List(ctx context.Context, userID string, limit int, offset int) ([]response.NotificationResponse, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []response.NotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]response.NotificationResponse, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []response.NotificationResponse); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.NotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NotificationService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *NotificationService_Expecter) List(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *NotificationService_List_Call {
	return &NotificationService_List_Call{Call: _e.mock.On("List", ctx, userID, limit, offset)}
}

func (_c *NotificationService_List_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *NotificationService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *NotificationService_List_Call) Return(_a0 []response.NotificationResponse, _a1 error) *NotificationService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationService_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]response.NotificationResponse, error)) *NotificationService_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *NotificationService) MarkAllRead(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type NotificationService_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *NotificationService_Expecter) MarkAllRead(ctx interface{}, userID interface{}) *NotificationService_MarkAllRead_Call {
	return &NotificationService_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *NotificationService_MarkAllRead_Call) Run(run func(ctx context.Context, userID string)) *NotificationService_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NotificationService_MarkAllRead_Call) Return(_a0 error) *NotificationService_MarkAllRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_MarkAllRead_Call) RunAndReturn(run func(context.Context, string) error) *NotificationService_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, userID, id
func (_m *NotificationService) MarkRead(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type NotificationService_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *NotificationService_Expecter) MarkRead(ctx interface{}, userID interface{}, id interface{}) *NotificationService_MarkRead_Call {
	return &NotificationService_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, id)}
}

func (_c *NotificationService_MarkRead_Call) Run(run func(ctx context.Context, userID string, id string)) *NotificationService_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *NotificationService_MarkRead_Call) Return(_a0 error) *NotificationService_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_MarkRead_Call) RunAndReturn(run func(context.Context, string, string) error) *NotificationService_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePreferences provides a mock function with given fields: ctx, userID, req
func (_m *NotificationService) UpdatePreferences(ctx context.Context, userID string, req request.UpdateNotificationPreferenceRequest) (*response.NotificationPreferenceResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 *response.NotificationPreferenceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.UpdateNotificationPreferenceRequest) (*response.NotificationPreferenceResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.UpdateNotificationPreferenceRequest) *response.NotificationPreferenceResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.NotificationPreferenceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.UpdateNotificationPreferenceRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationService_UpdatePreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePreferences'
type NotificationService_UpdatePreferences_Call struct {
	*mock.Call
}

// UpdatePreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.UpdateNotificationPreferenceRequest
func (_e *NotificationService_Expecter) UpdatePreferences(ctx interface{}, userID interface{}, req interface{}) *NotificationService_UpdatePreferences_Call {
	return &NotificationService_UpdatePreferences_Call{Call: _e.mock.On("UpdatePreferences", ctx, userID, req)}
}

func (_c *NotificationService_UpdatePreferences_Call) Run(run func(ctx context.Context, userID string, req request.UpdateNotificationPreferenceRequest)) *NotificationService_UpdatePreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.UpdateNotificationPreferenceRequest))
	})
	return _c
}

func (_c *NotificationService_UpdatePreferences_Call) Return(_a0 *response.NotificationPreferenceResponse, _a1 error) *NotificationService_UpdatePreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationService_UpdatePreferences_Call) RunAndReturn(run func(context.Context, string, request.UpdateNotificationPreferenceRequest) (*response.NotificationPreferenceResponse, error)) *NotificationService_UpdatePreferences_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
