// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	service "duitkita-api/service"

	mock "github.com/stretchr/testify/mock"
)

// OTPService is an autogenerated mock type for the OTPService type
type OTPService struct {
	mock.Mock
}

type OTPService_Expecter struct {
	mock *mock.Mock
}

func (_m *OTPService) EXPECT() *OTPService_Expecter {
	return &OTPService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, email, purpose
func (_m *OTPService) Generate(ctx context.Context, email string, purpose service.OTPPurpose) error {
	ret := _m.Called(ctx, email, purpose)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.OTPPurpose) error); ok {
		r0 = rf(ctx, email, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OTPService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type OTPService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - purpose service.OTPPurpose
func (_e *OTPService_Expecter) Generate(ctx interface{}, email interface{}, purpose interface{}) *OTPService_Generate_Call {
	return &OTPService_Generate_Call{Call: _e.mock.On("Generate", ctx, email, purpose)}
}

func (_c *OTPService_Generate_Call) Run(run func(ctx context.Context, email string, purpose service.OTPPurpose)) *OTPService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(service.OTPPurpose))
	})
	return _c
}

func (_c *OTPService_Generate_Call) Return(_a0 error) *OTPService_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OTPService_Generate_Call) RunAndReturn(run func(context.Context, string, service.OTPPurpose) error) *OTPService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, email, purpose, code
func (_m *OTPService) Verify(ctx context.Context, email string, purpose service.OTPPurpose, code string) error {
	ret := _m.Called(ctx, email, purpose, code)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.OTPPurpose, string) error); ok {
		r0 = rf(ctx, email, purpose, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OTPService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type OTPService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - purpose service.OTPPurpose
//   - code string
func (_e *OTPService_Expecter) Verify(ctx interface{}, email interface{}, purpose interface{}, code interface{}) *OTPService_Verify_Call {
	return &OTPService_Verify_Call{Call: _e.mock.On("Verify", ctx, email, purpose, code)}
}

func (_c *OTPService_Verify_Call) Run(run func(ctx context.Context, email string, purpose service.OTPPurpose, code string)) *OTPService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(service.OTPPurpose), args[3].(string))
	})
	return _c
}

func (_c *OTPService_Verify_Call) Return(_a0 error) *OTPService_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OTPService_Verify_Call) RunAndReturn(run func(context.Context, string, service.OTPPurpose, string) error) *OTPService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewOTPService creates a new instance of OTPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPService {
	mock := &OTPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
