// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Owned is an autogenerated mock type for the Owned type
type Owned struct {
	mock.Mock
}

type Owned_Expecter struct {
	mock *mock.Mock
}

func (_m *Owned) EXPECT() *Owned_Expecter {
	return &Owned_Expecter{mock: &_m.Mock}
}

// OwnerID provides a mock function with no fields
func (_m *Owned) OwnerID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OwnerID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Owned_OwnerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OwnerID'
type Owned_OwnerID_Call struct {
	*mock.Call
}

// OwnerID is a helper method to define mock.On call
func (_e *Owned_Expecter) OwnerID() *Owned_OwnerID_Call {
	return &Owned_OwnerID_Call{Call: _e.mock.On("OwnerID")}
}

func (_c *Owned_OwnerID_Call) Run(run func()) *Owned_OwnerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Owned_OwnerID_Call) Return(_a0 string) *Owned_OwnerID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Owned_OwnerID_Call) RunAndReturn(run func() string) *Owned_OwnerID_Call {
	_c.Call.Return(run)
	return _c
}

// NewOwned creates a new instance of Owned. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOwned(t interface {
	mock.TestingT
	Cleanup(func())
}) *Owned {
	mock := &Owned{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
