// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// RecurringExpenseService is an autogenerated mock type for the RecurringExpenseService type
type RecurringExpenseService struct {
	mock.Mock
}

type RecurringExpenseService_Expecter struct {
	mock *mock.Mock
}

func (_m *RecurringExpenseService) EXPECT() *RecurringExpenseService_Expecter {
	return &RecurringExpenseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *RecurringExpenseService) Create(ctx context.Context, userID string, req request.CreateRecurringExpenseRequest) (*response.RecurringExpenseResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.RecurringExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateRecurringExpenseRequest) (*response.RecurringExpenseResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateRecurringExpenseRequest) *response.RecurringExpenseResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.RecurringExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.CreateRecurringExpenseRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RecurringExpenseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.CreateRecurringExpenseRequest
func (_e *RecurringExpenseService_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *RecurringExpenseService_Create_Call {
	return &RecurringExpenseService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *RecurringExpenseService_Create_Call) Run(run func(ctx context.Context, userID string, req request.CreateRecurringExpenseRequest)) *RecurringExpenseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.CreateRecurringExpenseRequest))
	})
	return _c
}

func (_c *RecurringExpenseService_Create_Call) Return(_a0 *response.RecurringExpenseResponse, _a1 error) *RecurringExpenseService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseService_Create_Call) RunAndReturn(run func(context.Context, string, request.CreateRecurringExpenseRequest) (*response.RecurringExpenseResponse, error)) *RecurringExpenseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *RecurringExpenseService) Delete(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecurringExpenseService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RecurringExpenseService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *RecurringExpenseService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *RecurringExpenseService_Delete_Call {
	return &RecurringExpenseService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *RecurringExpenseService_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *RecurringExpenseService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RecurringExpenseService_Delete_Call) Return(_a0 error) *RecurringExpenseService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecurringExpenseService_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *RecurringExpenseService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *RecurringExpenseService) GetByID(ctx context.Context, userID string, id string) (*response.RecurringExpenseResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.RecurringExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.RecurringExpenseResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.RecurringExpenseResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.RecurringExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RecurringExpenseService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *RecurringExpenseService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *RecurringExpenseService_GetByID_Call {
	return &RecurringExpenseService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *RecurringExpenseService_GetByID_Call) Run(run func(ctx context.Context, userID string, id string)) *RecurringExpenseService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RecurringExpenseService_GetByID_Call) Return(_a0 *response.RecurringExpenseResponse, _a1 error) *RecurringExpenseService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseService_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*response.RecurringExpenseResponse, error)) *RecurringExpenseService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, limit, offset
func (_m *RecurringExpenseService) List(ctx context.Context, userID string, limit int, offset int) ([]response.RecurringExpenseResponse, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []response.RecurringExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]response.RecurringExpenseResponse, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []response.RecurringExpenseResponse); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.RecurringExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RecurringExpenseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *RecurringExpenseService_Expecter) List(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *RecurringExpenseService_List_Call {
	return &RecurringExpenseService_List_Call{Call: _e.mock.On("List", ctx, userID, limit, offset)}
}

func (_c *RecurringExpenseService_List_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *RecurringExpenseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *RecurringExpenseService_List_Call) Return(_a0 []response.RecurringExpenseResponse, _a1 error) *RecurringExpenseService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseService_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]response.RecurringExpenseResponse, error)) *RecurringExpenseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function with given fields: ctx, userID, id
func (_m *RecurringExpenseService) Pause(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecurringExpenseService_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type RecurringExpenseService_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *RecurringExpenseService_Expecter) Pause(ctx interface{}, userID interface{}, id interface{}) *RecurringExpenseService_Pause_Call {
	return &RecurringExpenseService_Pause_Call{Call: _e.mock.On("Pause", ctx, userID, id)}
}

func (_c *RecurringExpenseService_Pause_Call) Run(run func(ctx context.Context, userID string, id string)) *RecurringExpenseService_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RecurringExpenseService_Pause_Call) Return(_a0 error) *RecurringExpenseService_Pause_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecurringExpenseService_Pause_Call) RunAndReturn(run func(context.Context, string, string) error) *RecurringExpenseService_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function with given fields: ctx, userID, id
func (_m *RecurringExpenseService) Resume(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecurringExpenseService_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type RecurringExpenseService_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *RecurringExpenseService_Expecter) Resume(ctx interface{}, userID interface{}, id interface{}) *RecurringExpenseService_Resume_Call {
	return &RecurringExpenseService_Resume_Call{Call: _e.mock.On("Resume", ctx, userID, id)}
}

func (_c *RecurringExpenseService_Resume_Call) Run(run func(ctx context.Context, userID string, id string)) *RecurringExpenseService_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RecurringExpenseService_Resume_Call) Return(_a0 error) *RecurringExpenseService_Resume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecurringExpenseService_Resume_Call) RunAndReturn(run func(context.Context, string, string) error) *RecurringExpenseService_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// RunDue provides a mock function with given fields: ctx
func (_m *RecurringExpenseService) RunDue(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunDue")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseService_RunDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunDue'
type RecurringExpenseService_RunDue_Call struct {
	*mock.Call
}

// RunDue is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RecurringExpenseService_Expecter) RunDue(ctx interface{}) *RecurringExpenseService_RunDue_Call {
	return &RecurringExpenseService_RunDue_Call{Call: _e.mock.On("RunDue", ctx)}
}

func (_c *RecurringExpenseService_RunDue_Call) Run(run func(ctx context.Context)) *RecurringExpenseService_RunDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RecurringExpenseService_RunDue_Call) Return(_a0 int, _a1 error) *RecurringExpenseService_RunDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseService_RunDue_Call) RunAndReturn(run func(context.Context) (int, error)) *RecurringExpenseService_RunDue_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, id, req
func (_m *RecurringExpenseService) Update(ctx context.Context, userID string, id string, req request.UpdateRecurringExpenseRequest) (*response.RecurringExpenseResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *response.RecurringExpenseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateRecurringExpenseRequest) (*response.RecurringExpenseResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateRecurringExpenseRequest) *response.RecurringExpenseResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.RecurringExpenseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, request.UpdateRecurringExpenseRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurringExpenseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RecurringExpenseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - req request.UpdateRecurringExpenseRequest
func (_e *RecurringExpenseService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, req interface{}) *RecurringExpenseService_Update_Call {
	return &RecurringExpenseService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, req)}
}

func (_c *RecurringExpenseService_Update_Call) Run(run func(ctx context.Context, userID string, id string, req request.UpdateRecurringExpenseRequest)) *RecurringExpenseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request.UpdateRecurringExpenseRequest))
	})
	return _c
}

func (_c *RecurringExpenseService_Update_Call) Return(_a0 *response.RecurringExpenseResponse, _a1 error) *RecurringExpenseService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecurringExpenseService_Update_Call) RunAndReturn(run func(context.Context, string, string, request.UpdateRecurringExpenseRequest) (*response.RecurringExpenseResponse, error)) *RecurringExpenseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecurringExpenseService creates a new instance of RecurringExpenseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecurringExpenseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecurringExpenseService {
	mock := &RecurringExpenseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
