// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// ReminderService is an autogenerated mock type for the ReminderService type
type ReminderService struct {
	mock.Mock
}

type ReminderService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReminderService) EXPECT() *ReminderService_Expecter {
	return &ReminderService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *ReminderService) Create(ctx context.Context, userID string, req request.CreateReminderRequest) (*response.ReminderResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.ReminderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateReminderRequest) (*response.ReminderResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateReminderRequest) *response.ReminderResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ReminderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.CreateReminderRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReminderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.CreateReminderRequest
func (_e *ReminderService_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *ReminderService_Create_Call {
	return &ReminderService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *ReminderService_Create_Call) Run(run func(ctx context.Context, userID string, req request.CreateReminderRequest)) *ReminderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.CreateReminderRequest))
	})
	return _c
}

func (_c *ReminderService_Create_Call) Return(_a0 *response.ReminderResponse, _a1 error) *ReminderService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderService_Create_Call) RunAndReturn(run func(context.Context, string, request.CreateReminderRequest) (*response.ReminderResponse, error)) *ReminderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *ReminderService) Delete(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReminderService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReminderService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ReminderService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *ReminderService_Delete_Call {
	return &ReminderService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *ReminderService_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *ReminderService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReminderService_Delete_Call) Return(_a0 error) *ReminderService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReminderService_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *ReminderService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *ReminderService) GetByID(ctx context.Context, userID string, id string) (*response.ReminderResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.ReminderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.ReminderResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.ReminderResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ReminderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ReminderService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ReminderService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *ReminderService_GetByID_Call {
	return &ReminderService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *ReminderService_GetByID_Call) Run(run func(ctx context.Context, userID string, id string)) *ReminderService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReminderService_GetByID_Call) Return(_a0 *response.ReminderResponse, _a1 error) *ReminderService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderService_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*response.ReminderResponse, error)) *ReminderService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, limit, offset
func (_m *ReminderService) List(ctx context.Context, userID string, limit int, offset int) ([]response.ReminderResponse, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []response.ReminderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]response.ReminderResponse, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []response.ReminderResponse); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.ReminderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ReminderService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *ReminderService_Expecter) List(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *ReminderService_List_Call {
	return &ReminderService_List_Call{Call: _e.mock.On("List", ctx, userID, limit, offset)}
}

func (_c *ReminderService_List_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *ReminderService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReminderService_List_Call) Return(_a0 []response.ReminderResponse, _a1 error) *ReminderService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderService_List_Call) RunAndReturn(run func(context.Context, string, int, int) ([]response.ReminderResponse, error)) *ReminderService_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDone provides a mock function with given fields: ctx, userID, id
func (_m *ReminderService) MarkDone(ctx context.Context, userID string, id string) (*response.ReminderResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkDone")
	}

	var r0 *response.ReminderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.ReminderResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.ReminderResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ReminderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderService_MarkDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDone'
type ReminderService_MarkDone_Call struct {
	*mock.Call
}

// MarkDone is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ReminderService_Expecter) MarkDone(ctx interface{}, userID interface{}, id interface{}) *ReminderService_MarkDone_Call {
	return &ReminderService_MarkDone_Call{Call: _e.mock.On("MarkDone", ctx, userID, id)}
}

func (_c *ReminderService_MarkDone_Call) Run(run func(ctx context.Context, userID string, id string)) *ReminderService_MarkDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReminderService_MarkDone_Call) Return(_a0 *response.ReminderResponse, _a1 error) *ReminderService_MarkDone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderService_MarkDone_Call) RunAndReturn(run func(context.Context, string, string) (*response.ReminderResponse, error)) *ReminderService_MarkDone_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessDue provides a mock function with given fields: ctx
func (_m *ReminderService) ProcessDue(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessDue")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderService_ProcessDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessDue'
type ReminderService_ProcessDue_Call struct {
	*mock.Call
}

// ProcessDue is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReminderService_Expecter) ProcessDue(ctx interface{}) *ReminderService_ProcessDue_Call {
	return &ReminderService_ProcessDue_Call{Call: _e.mock.On("ProcessDue", ctx)}
}

func (_c *ReminderService_ProcessDue_Call) Run(run func(ctx context.Context)) *ReminderService_ProcessDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReminderService_ProcessDue_Call) Return(_a0 int, _a1 error) *ReminderService_ProcessDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderService_ProcessDue_Call) RunAndReturn(run func(context.Context) (int, error)) *ReminderService_ProcessDue_Call {
	_c.Call.Return(run)
	return _c
}

// Snooze provides a mock function with given fields: ctx, userID, id, req
func (_m *ReminderService) Snooze(ctx context.Context, userID string, id string, req request.SnoozeReminderRequest) (*response.ReminderResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Snooze")
	}

	var r0 *response.ReminderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.SnoozeReminderRequest) (*response.ReminderResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.SnoozeReminderRequest) *response.ReminderResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ReminderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, request.SnoozeReminderRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderService_Snooze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snooze'
type ReminderService_Snooze_Call struct {
	*mock.Call
}

// Snooze is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - req request.SnoozeReminderRequest
func (_e *ReminderService_Expecter) Snooze(ctx interface{}, userID interface{}, id interface{}, req interface{}) *ReminderService_Snooze_Call {
	return &ReminderService_Snooze_Call{Call: _e.mock.On("Snooze", ctx, userID, id, req)}
}

func (_c *ReminderService_Snooze_Call) Run(run func(ctx context.Context, userID string, id string, req request.SnoozeReminderRequest)) *ReminderService_Snooze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request.SnoozeReminderRequest))
	})
	return _c
}

func (_c *ReminderService_Snooze_Call) Return(_a0 *response.ReminderResponse, _a1 error) *ReminderService_Snooze_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderService_Snooze_Call) RunAndReturn(run func(context.Context, string, string, request.SnoozeReminderRequest) (*response.ReminderResponse, error)) *ReminderService_Snooze_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, id, req
func (_m *ReminderService) Update(ctx context.Context, userID string, id string, req request.UpdateReminderRequest) (*response.ReminderResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *response.ReminderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateReminderRequest) (*response.ReminderResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, request.UpdateReminderRequest) *response.ReminderResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ReminderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, request.UpdateReminderRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReminderService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ReminderService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - req request.UpdateReminderRequest
func (_e *ReminderService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, req interface{}) *ReminderService_Update_Call {
	return &ReminderService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, req)}
}

func (_c *ReminderService_Update_Call) Run(run func(ctx context.Context, userID string, id string, req request.UpdateReminderRequest)) *ReminderService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(request.UpdateReminderRequest))
	})
	return _c
}

func (_c *ReminderService_Update_Call) Return(_a0 *response.ReminderResponse, _a1 error) *ReminderService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReminderService_Update_Call) RunAndReturn(run func(context.Context, string, string, request.UpdateReminderRequest) (*response.ReminderResponse, error)) *ReminderService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewReminderService creates a new instance of ReminderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReminderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReminderService {
	mock := &ReminderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
