// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// ReportService is an autogenerated mock type for the ReportService type
type ReportService struct {
	mock.Mock
}

type ReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportService) EXPECT() *ReportService_Expecter {
	return &ReportService_Expecter{mock: &_m.Mock}
}

// CoupleReport provides a mock function with given fields: ctx, userID, year, month
func (_m *ReportService) CoupleReport(ctx context.Context, userID string, year int, month int) (*response.CoupleReportResponse, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for CoupleReport")
	}

	var r0 *response.CoupleReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*response.CoupleReportResponse, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *response.CoupleReportResponse); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CoupleReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_CoupleReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoupleReport'
type ReportService_CoupleReport_Call struct {
	*mock.Call
}

// CoupleReport is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *ReportService_Expecter) CoupleReport(ctx interface{}, userID interface{}, year interface{}, month interface{}) *ReportService_CoupleReport_Call {
	return &ReportService_CoupleReport_Call{Call: _e.mock.On("CoupleReport", ctx, userID, year, month)}
}

func (_c *ReportService_CoupleReport_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *ReportService_CoupleReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReportService_CoupleReport_Call) Return(_a0 *response.CoupleReportResponse, _a1 error) *ReportService_CoupleReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_CoupleReport_Call) RunAndReturn(run func(context.Context, string, int, int) (*response.CoupleReportResponse, error)) *ReportService_CoupleReport_Call {
	_c.Call.Return(run)
	return _c
}

// CoupleTrend provides a mock function with given fields: ctx, userID, months
func (_m *ReportService) CoupleTrend(ctx context.Context, userID string, months int) (*response.TrendResponse, error) {
	ret := _m.Called(ctx, userID, months)

	if len(ret) == 0 {
		panic("no return value specified for CoupleTrend")
	}

	var r0 *response.TrendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*response.TrendResponse, error)); ok {
		return rf(ctx, userID, months)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *response.TrendResponse); ok {
		r0 = rf(ctx, userID, months)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.TrendResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, months)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_CoupleTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoupleTrend'
type ReportService_CoupleTrend_Call struct {
	*mock.Call
}

// CoupleTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - months int
func (_e *ReportService_Expecter) CoupleTrend(ctx interface{}, userID interface{}, months interface{}) *ReportService_CoupleTrend_Call {
	return &ReportService_CoupleTrend_Call{Call: _e.mock.On("CoupleTrend", ctx, userID, months)}
}

func (_c *ReportService_CoupleTrend_Call) Run(run func(ctx context.Context, userID string, months int)) *ReportService_CoupleTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ReportService_CoupleTrend_Call) Return(_a0 *response.TrendResponse, _a1 error) *ReportService_CoupleTrend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_CoupleTrend_Call) RunAndReturn(run func(context.Context, string, int) (*response.TrendResponse, error)) *ReportService_CoupleTrend_Call {
	_c.Call.Return(run)
	return _c
}

// DailyBreakdown provides a mock function with given fields: ctx, userID, year, month
func (_m *ReportService) DailyBreakdown(ctx context.Context, userID string, year int, month int) (*response.DailyReportResponse, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for DailyBreakdown")
	}

	var r0 *response.DailyReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*response.DailyReportResponse, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *response.DailyReportResponse); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.DailyReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_DailyBreakdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DailyBreakdown'
type ReportService_DailyBreakdown_Call struct {
	*mock.Call
}

// DailyBreakdown is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *ReportService_Expecter) DailyBreakdown(ctx interface{}, userID interface{}, year interface{}, month interface{}) *ReportService_DailyBreakdown_Call {
	return &ReportService_DailyBreakdown_Call{Call: _e.mock.On("DailyBreakdown", ctx, userID, year, month)}
}

func (_c *ReportService_DailyBreakdown_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *ReportService_DailyBreakdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReportService_DailyBreakdown_Call) Return(_a0 *response.DailyReportResponse, _a1 error) *ReportService_DailyBreakdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_DailyBreakdown_Call) RunAndReturn(run func(context.Context, string, int, int) (*response.DailyReportResponse, error)) *ReportService_DailyBreakdown_Call {
	_c.Call.Return(run)
	return _c
}

// MonthlyReport provides a mock function with given fields: ctx, userID, year, month
func (_m *ReportService) MonthlyReport(ctx context.Context, userID string, year int, month int) (*response.MonthlyReportResponse, error) {
	ret := _m.Called(ctx, userID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for MonthlyReport")
	}

	var r0 *response.MonthlyReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*response.MonthlyReportResponse, error)); ok {
		return rf(ctx, userID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *response.MonthlyReportResponse); ok {
		r0 = rf(ctx, userID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.MonthlyReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_MonthlyReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonthlyReport'
type ReportService_MonthlyReport_Call struct {
	*mock.Call
}

// MonthlyReport is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - year int
//   - month int
func (_e *ReportService_Expecter) MonthlyReport(ctx interface{}, userID interface{}, year interface{}, month interface{}) *ReportService_MonthlyReport_Call {
	return &ReportService_MonthlyReport_Call{Call: _e.mock.On("MonthlyReport", ctx, userID, year, month)}
}

func (_c *ReportService_MonthlyReport_Call) Run(run func(ctx context.Context, userID string, year int, month int)) *ReportService_MonthlyReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ReportService_MonthlyReport_Call) Return(_a0 *response.MonthlyReportResponse, _a1 error) *ReportService_MonthlyReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_MonthlyReport_Call) RunAndReturn(run func(context.Context, string, int, int) (*response.MonthlyReportResponse, error)) *ReportService_MonthlyReport_Call {
	_c.Call.Return(run)
	return _c
}

// Rollover provides a mock function with given fields: ctx, userID, categoryID, year, month
func (_m *ReportService) Rollover(ctx context.Context, userID string, categoryID string, year int, month int) (int64, error) {
	ret := _m.Called(ctx, userID, categoryID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for Rollover")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) (int64, error)); ok {
		return rf(ctx, userID, categoryID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) int64); ok {
		r0 = rf(ctx, userID, categoryID, year, month)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, userID, categoryID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_Rollover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollover'
type ReportService_Rollover_Call struct {
	*mock.Call
}

// Rollover is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - categoryID string
//   - year int
//   - month int
func (_e *ReportService_Expecter) Rollover(ctx interface{}, userID interface{}, categoryID interface{}, year interface{}, month interface{}) *ReportService_Rollover_Call {
	return &ReportService_Rollover_Call{Call: _e.mock.On("Rollover", ctx, userID, categoryID, year, month)}
}

func (_c *ReportService_Rollover_Call) Run(run func(ctx context.Context, userID string, categoryID string, year int, month int)) *ReportService_Rollover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *ReportService_Rollover_Call) Return(_a0 int64, _a1 error) *ReportService_Rollover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_Rollover_Call) RunAndReturn(run func(context.Context, string, string, int, int) (int64, error)) *ReportService_Rollover_Call {
	_c.Call.Return(run)
	return _c
}

// Trend provides a mock function with given fields: ctx, userID, months
func (_m *ReportService) Trend(ctx context.Context, userID string, months int) (*response.TrendResponse, error) {
	ret := _m.Called(ctx, userID, months)

	if len(ret) == 0 {
		panic("no return value specified for Trend")
	}

	var r0 *response.TrendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*response.TrendResponse, error)); ok {
		return rf(ctx, userID, months)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *response.TrendResponse); ok {
		r0 = rf(ctx, userID, months)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.TrendResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, months)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_Trend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trend'
type ReportService_Trend_Call struct {
	*mock.Call
}

// Trend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - months int
func (_e *ReportService_Expecter) Trend(ctx interface{}, userID interface{}, months interface{}) *ReportService_Trend_Call {
	return &ReportService_Trend_Call{Call: _e.mock.On("Trend", ctx, userID, months)}
}

func (_c *ReportService_Trend_Call) Run(run func(ctx context.Context, userID string, months int)) *ReportService_Trend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ReportService_Trend_Call) Return(_a0 *response.TrendResponse, _a1 error) *ReportService_Trend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_Trend_Call) RunAndReturn(run func(context.Context, string, int) (*response.TrendResponse, error)) *ReportService_Trend_Call {
	_c.Call.Return(run)
	return _c
}

// TrendByCategory provides a mock function with given fields: ctx, userID, categoryID, months
func (_m *ReportService) TrendByCategory(ctx context.Context, userID string, categoryID string, months int) (*response.TrendResponse, error) {
	ret := _m.Called(ctx, userID, categoryID, months)

	if len(ret) == 0 {
		panic("no return value specified for TrendByCategory")
	}

	var r0 *response.TrendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*response.TrendResponse, error)); ok {
		return rf(ctx, userID, categoryID, months)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *response.TrendResponse); ok {
		r0 = rf(ctx, userID, categoryID, months)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.TrendResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, userID, categoryID, months)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_TrendByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrendByCategory'
type ReportService_TrendByCategory_Call struct {
	*mock.Call
}

// TrendByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - categoryID string
//   - months int
func (_e *ReportService_Expecter) TrendByCategory(ctx interface{}, userID interface{}, categoryID interface{}, months interface{}) *ReportService_TrendByCategory_Call {
	return &ReportService_TrendByCategory_Call{Call: _e.mock.On("TrendByCategory", ctx, userID, categoryID, months)}
}

func (_c *ReportService_TrendByCategory_Call) Run(run func(ctx context.Context, userID string, categoryID string, months int)) *ReportService_TrendByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *ReportService_TrendByCategory_Call) Return(_a0 *response.TrendResponse, _a1 error) *ReportService_TrendByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_TrendByCategory_Call) RunAndReturn(run func(context.Context, string, string, int) (*response.TrendResponse, error)) *ReportService_TrendByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportService creates a new instance of ReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportService {
	mock := &ReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
