// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// ReportExportService is an autogenerated mock type for the ReportExportService type
type ReportExportService struct {
	mock.Mock
}

type ReportExportService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportExportService) EXPECT() *ReportExportService_Expecter {
	return &ReportExportService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *ReportExportService) Create(ctx context.Context, userID string, req request.CreateExportRequest) (*response.ExportResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.ExportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateExportRequest) (*response.ExportResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.CreateExportRequest) *response.ExportResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ExportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.CreateExportRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReportExportService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.CreateExportRequest
func (_e *ReportExportService_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *ReportExportService_Create_Call {
	return &ReportExportService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *ReportExportService_Create_Call) Run(run func(ctx context.Context, userID string, req request.CreateExportRequest)) *ReportExportService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.CreateExportRequest))
	})
	return _c
}

func (_c *ReportExportService_Create_Call) Return(_a0 *response.ExportResponse, _a1 error) *ReportExportService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportService_Create_Call) RunAndReturn(run func(context.Context, string, request.CreateExportRequest) (*response.ExportResponse, error)) *ReportExportService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadURL provides a mock function with given fields: ctx, userID, id
func (_m *ReportExportService) DownloadURL(ctx context.Context, userID string, id string) (string, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DownloadURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportService_DownloadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadURL'
type ReportExportService_DownloadURL_Call struct {
	*mock.Call
}

// DownloadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ReportExportService_Expecter) DownloadURL(ctx interface{}, userID interface{}, id interface{}) *ReportExportService_DownloadURL_Call {
	return &ReportExportService_DownloadURL_Call{Call: _e.mock.On("DownloadURL", ctx, userID, id)}
}

func (_c *ReportExportService_DownloadURL_Call) Run(run func(ctx context.Context, userID string, id string)) *ReportExportService_DownloadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReportExportService_DownloadURL_Call) Return(_a0 string, _a1 error) *ReportExportService_DownloadURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportService_DownloadURL_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *ReportExportService_DownloadURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *ReportExportService) GetByID(ctx context.Context, userID string, id string) (*response.ExportResponse, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *response.ExportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.ExportResponse, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.ExportResponse); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ExportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ReportExportService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *ReportExportService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *ReportExportService_GetByID_Call {
	return &ReportExportService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *ReportExportService_GetByID_Call) Run(run func(ctx context.Context, userID string, id string)) *ReportExportService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReportExportService_GetByID_Call) Return(_a0 *response.ExportResponse, _a1 error) *ReportExportService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportService_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*response.ExportResponse, error)) *ReportExportService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *ReportExportService) List(ctx context.Context, userID string) ([]response.ExportResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []response.ExportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]response.ExportResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []response.ExportResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.ExportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ReportExportService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ReportExportService_Expecter) List(ctx interface{}, userID interface{}) *ReportExportService_List_Call {
	return &ReportExportService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *ReportExportService_List_Call) Run(run func(ctx context.Context, userID string)) *ReportExportService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReportExportService_List_Call) Return(_a0 []response.ExportResponse, _a1 error) *ReportExportService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportService_List_Call) RunAndReturn(run func(context.Context, string) ([]response.ExportResponse, error)) *ReportExportService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessPending provides a mock function with given fields: ctx
func (_m *ReportExportService) ProcessPending(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPending")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportExportService_ProcessPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPending'
type ReportExportService_ProcessPending_Call struct {
	*mock.Call
}

// ProcessPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportExportService_Expecter) ProcessPending(ctx interface{}) *ReportExportService_ProcessPending_Call {
	return &ReportExportService_ProcessPending_Call{Call: _e.mock.On("ProcessPending", ctx)}
}

func (_c *ReportExportService_ProcessPending_Call) Run(run func(ctx context.Context)) *ReportExportService_ProcessPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportExportService_ProcessPending_Call) Return(_a0 int, _a1 error) *ReportExportService_ProcessPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportExportService_ProcessPending_Call) RunAndReturn(run func(context.Context) (int, error)) *ReportExportService_ProcessPending_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportExportService creates a new instance of ReportExportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportExportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportExportService {
	mock := &ReportExportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
