// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// SecurityAuditService is an autogenerated mock type for the SecurityAuditService type
type SecurityAuditService struct {
	mock.Mock
}

type SecurityAuditService_Expecter struct {
	mock *mock.Mock
}

func (_m *SecurityAuditService) EXPECT() *SecurityAuditService_Expecter {
	return &SecurityAuditService_Expecter{mock: &_m.Mock}
}

// ListByUser provides a mock function with given fields: ctx, userID, limit
func (_m *SecurityAuditService) ListByUser(ctx context.Context, userID string, limit int) ([]domain.SecurityAuditLog, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.SecurityAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.SecurityAuditLog, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.SecurityAuditLog); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SecurityAuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecurityAuditService_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type SecurityAuditService_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
func (_e *SecurityAuditService_Expecter) ListByUser(ctx interface{}, userID interface{}, limit interface{}) *SecurityAuditService_ListByUser_Call {
	return &SecurityAuditService_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, limit)}
}

func (_c *SecurityAuditService_ListByUser_Call) Run(run func(ctx context.Context, userID string, limit int)) *SecurityAuditService_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *SecurityAuditService_ListByUser_Call) Return(_a0 []domain.SecurityAuditLog, _a1 error) *SecurityAuditService_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecurityAuditService_ListByUser_Call) RunAndReturn(run func(context.Context, string, int) ([]domain.SecurityAuditLog, error)) *SecurityAuditService_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// LogEvent provides a mock function with given fields: ctx, userID, eventType, ipAddress, userAgent, meta
func (_m *SecurityAuditService) LogEvent(ctx context.Context, userID *string, eventType domain.SecurityAuditEventType, ipAddress string, userAgent string, meta map[string]interface{}) {
	_m.Called(ctx, userID, eventType, ipAddress, userAgent, meta)
}

// SecurityAuditService_LogEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogEvent'
type SecurityAuditService_LogEvent_Call struct {
	*mock.Call
}

// LogEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *string
//   - eventType domain.SecurityAuditEventType
//   - ipAddress string
//   - userAgent string
//   - meta map[string]interface{}
func (_e *SecurityAuditService_Expecter) LogEvent(ctx interface{}, userID interface{}, eventType interface{}, ipAddress interface{}, userAgent interface{}, meta interface{}) *SecurityAuditService_LogEvent_Call {
	return &SecurityAuditService_LogEvent_Call{Call: _e.mock.On("LogEvent", ctx, userID, eventType, ipAddress, userAgent, meta)}
}

func (_c *SecurityAuditService_LogEvent_Call) Run(run func(ctx context.Context, userID *string, eventType domain.SecurityAuditEventType, ipAddress string, userAgent string, meta map[string]interface{})) *SecurityAuditService_LogEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(domain.SecurityAuditEventType), args[3].(string), args[4].(string), args[5].(map[string]interface{}))
	})
	return _c
}

func (_c *SecurityAuditService_LogEvent_Call) Return() *SecurityAuditService_LogEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *SecurityAuditService_LogEvent_Call) RunAndReturn(run func(context.Context, *string, domain.SecurityAuditEventType, string, string, map[string]interface{})) *SecurityAuditService_LogEvent_Call {
	_c.Run(run)
	return _c
}

// NewSecurityAuditService creates a new instance of SecurityAuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityAuditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityAuditService {
	mock := &SecurityAuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
