// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TaskEnqueuer is an autogenerated mock type for the TaskEnqueuer type
type TaskEnqueuer struct {
	mock.Mock
}

type TaskEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskEnqueuer) EXPECT() *TaskEnqueuer_Expecter {
	return &TaskEnqueuer_Expecter{mock: &_m.Mock}
}

// EnqueueReportExportRender provides a mock function with given fields: ctx, exportID
func (_m *TaskEnqueuer) EnqueueReportExportRender(ctx context.Context, exportID string) error {
	ret := _m.Called(ctx, exportID)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueReportExportRender")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, exportID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskEnqueuer_EnqueueReportExportRender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueReportExportRender'
type TaskEnqueuer_EnqueueReportExportRender_Call struct {
	*mock.Call
}

// EnqueueReportExportRender is a helper method to define mock.On call
//   - ctx context.Context
//   - exportID string
func (_e *TaskEnqueuer_Expecter) EnqueueReportExportRender(ctx interface{}, exportID interface{}) *TaskEnqueuer_EnqueueReportExportRender_Call {
	return &TaskEnqueuer_EnqueueReportExportRender_Call{Call: _e.mock.On("EnqueueReportExportRender", ctx, exportID)}
}

func (_c *TaskEnqueuer_EnqueueReportExportRender_Call) Run(run func(ctx context.Context, exportID string)) *TaskEnqueuer_EnqueueReportExportRender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TaskEnqueuer_EnqueueReportExportRender_Call) Return(_a0 error) *TaskEnqueuer_EnqueueReportExportRender_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskEnqueuer_EnqueueReportExportRender_Call) RunAndReturn(run func(context.Context, string) error) *TaskEnqueuer_EnqueueReportExportRender_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskEnqueuer creates a new instance of TaskEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskEnqueuer {
	mock := &TaskEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
