// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "duitkita-api/model/domain"
	request "duitkita-api/model/dto/request"
	response "duitkita-api/model/dto/response"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, req
func (_m *UserService) ChangePassword(ctx context.Context, userID string, req request.ChangePasswordRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.ChangePasswordRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type UserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.ChangePasswordRequest
func (_e *UserService_Expecter) ChangePassword(ctx interface{}, userID interface{}, req interface{}) *UserService_ChangePassword_Call {
	return &UserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, req)}
}

func (_c *UserService_ChangePassword_Call) Run(run func(ctx context.Context, userID string, req request.ChangePasswordRequest)) *UserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.ChangePasswordRequest))
	})
	return _c
}

func (_c *UserService_ChangePassword_Call) Return(_a0 error) *UserService_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserService_ChangePassword_Call) RunAndReturn(run func(context.Context, string, request.ChangePasswordRequest) error) *UserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAvatar provides a mock function with given fields: ctx, userID
func (_m *UserService) DeleteAvatar(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserService_DeleteAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAvatar'
type UserService_DeleteAvatar_Call struct {
	*mock.Call
}

// DeleteAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserService_Expecter) DeleteAvatar(ctx interface{}, userID interface{}) *UserService_DeleteAvatar_Call {
	return &UserService_DeleteAvatar_Call{Call: _e.mock.On("DeleteAvatar", ctx, userID)}
}

func (_c *UserService_DeleteAvatar_Call) Run(run func(ctx context.Context, userID string)) *UserService_DeleteAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_DeleteAvatar_Call) Return(_a0 error) *UserService_DeleteAvatar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserService_DeleteAvatar_Call) RunAndReturn(run func(context.Context, string) error) *UserService_DeleteAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatarURL provides a mock function with given fields: ctx, userID
func (_m *UserService) GetAvatarURL(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetAvatarURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatarURL'
type UserService_GetAvatarURL_Call struct {
	*mock.Call
}

// GetAvatarURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserService_Expecter) GetAvatarURL(ctx interface{}, userID interface{}) *UserService_GetAvatarURL_Call {
	return &UserService_GetAvatarURL_Call{Call: _e.mock.On("GetAvatarURL", ctx, userID)}
}

func (_c *UserService_GetAvatarURL_Call) Run(run func(ctx context.Context, userID string)) *UserService_GetAvatarURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_GetAvatarURL_Call) Return(_a0 string, _a1 error) *UserService_GetAvatarURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetAvatarURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *UserService_GetAvatarURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *UserService) GetProfile(ctx context.Context, userID string) (*response.UserResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.UserResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.UserResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type UserService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserService_Expecter) GetProfile(ctx interface{}, userID interface{}) *UserService_GetProfile_Call {
	return &UserService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *UserService_GetProfile_Call) Run(run func(ctx context.Context, userID string)) *UserService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_GetProfile_Call) Return(_a0 *response.UserResponse, _a1 error) *UserService_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetProfile_Call) RunAndReturn(run func(context.Context, string) (*response.UserResponse, error)) *UserService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecurityAudit provides a mock function with given fields: ctx, userID
func (_m *UserService) GetSecurityAudit(ctx context.Context, userID string) ([]domain.SecurityAuditLog, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecurityAudit")
	}

	var r0 []domain.SecurityAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.SecurityAuditLog, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.SecurityAuditLog); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SecurityAuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetSecurityAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecurityAudit'
type UserService_GetSecurityAudit_Call struct {
	*mock.Call
}

// GetSecurityAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserService_Expecter) GetSecurityAudit(ctx interface{}, userID interface{}) *UserService_GetSecurityAudit_Call {
	return &UserService_GetSecurityAudit_Call{Call: _e.mock.On("GetSecurityAudit", ctx, userID)}
}

func (_c *UserService_GetSecurityAudit_Call) Run(run func(ctx context.Context, userID string)) *UserService_GetSecurityAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_GetSecurityAudit_Call) Return(_a0 []domain.SecurityAuditLog, _a1 error) *UserService_GetSecurityAudit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetSecurityAudit_Call) RunAndReturn(run func(context.Context, string) ([]domain.SecurityAuditLog, error)) *UserService_GetSecurityAudit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *UserService) UpdateProfile(ctx context.Context, userID string, req request.UpdateProfileRequest) (*response.UserResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.UpdateProfileRequest) (*response.UserResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, request.UpdateProfileRequest) *response.UserResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, request.UpdateProfileRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req request.UpdateProfileRequest
func (_e *UserService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *UserService_UpdateProfile_Call {
	return &UserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *UserService_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, req request.UpdateProfileRequest)) *UserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(request.UpdateProfileRequest))
	})
	return _c
}

func (_c *UserService_UpdateProfile_Call) Return(_a0 *response.UserResponse, _a1 error) *UserService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, request.UpdateProfileRequest) (*response.UserResponse, error)) *UserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAvatar provides a mock function with given fields: ctx, userID, file, header
func (_m *UserService) UploadAvatar(ctx context.Context, userID string, file multipart.File, header *multipart.FileHeader) (*response.UserResponse, error) {
	ret := _m.Called(ctx, userID, file, header)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 *response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File, *multipart.FileHeader) (*response.UserResponse, error)); ok {
		return rf(ctx, userID, file, header)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File, *multipart.FileHeader) *response.UserResponse); ok {
		r0 = rf(ctx, userID, file, header)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, multipart.File, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, userID, file, header)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_UploadAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAvatar'
type UserService_UploadAvatar_Call struct {
	*mock.Call
}

// UploadAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - file multipart.File
//   - header *multipart.FileHeader
func (_e *UserService_Expecter) UploadAvatar(ctx interface{}, userID interface{}, file interface{}, header interface{}) *UserService_UploadAvatar_Call {
	return &UserService_UploadAvatar_Call{Call: _e.mock.On("UploadAvatar", ctx, userID, file, header)}
}

func (_c *UserService_UploadAvatar_Call) Run(run func(ctx context.Context, userID string, file multipart.File, header *multipart.FileHeader)) *UserService_UploadAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(multipart.File), args[3].(*multipart.FileHeader))
	})
	return _c
}

func (_c *UserService_UploadAvatar_Call) Return(_a0 *response.UserResponse, _a1 error) *UserService_UploadAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_UploadAvatar_Call) RunAndReturn(run func(context.Context, string, multipart.File, *multipart.FileHeader) (*response.UserResponse, error)) *UserService_UploadAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
